/*
***************************   C DATA TYPE   *******************************
**                                                                             
**  project     : C Data Types Extension                                                
**  filename  : CDATPIC24.H                                                                
**                                                                                                               
***************************************************************************
*/

#ifndef   CDATPIC24_INCLUDED
#define   CDATPIC24_INCLUDED

/*
***************************************************************************
                            C  TYPEDEFS                                           
***************************************************************************
*/

/**** C type extensions ****/
typedef unsigned char      int8u;
typedef signed   char      int8s;
typedef unsigned int       int16u;
typedef signed   int       int16s;
typedef unsigned long      int32u;
typedef signed   long      int32s;
typedef unsigned long long int64u;
typedef signed   long long int64s;


#endif
/*
**************************************************************************
                               EOF                                                   
/*************************************************************************
*/

