# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'SetPostureHumanoidUI_QT5.ui'
#
# Created by: PyQt5 UI code generator 5.9
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(985, 759)
        self.verticalLayoutWidget_7 = QtWidgets.QWidget(Form)
        self.verticalLayoutWidget_7.setGeometry(QtCore.QRect(10, 550, 471, 201))
        self.verticalLayoutWidget_7.setObjectName("verticalLayoutWidget_7")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_7)
        self.verticalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.horizontalLayout_26 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_26.setObjectName("horizontalLayout_26")
        self.setLArmAll_pushButton = QtWidgets.QPushButton(self.verticalLayoutWidget_7)
        self.setLArmAll_pushButton.setObjectName("setLArmAll_pushButton")
        self.horizontalLayout_26.addWidget(self.setLArmAll_pushButton)
        self.getLArmAll_pushButton = QtWidgets.QPushButton(self.verticalLayoutWidget_7)
        self.getLArmAll_pushButton.setObjectName("getLArmAll_pushButton")
        self.horizontalLayout_26.addWidget(self.getLArmAll_pushButton)
        self.disTLArmAll_pushButton = QtWidgets.QPushButton(self.verticalLayoutWidget_7)
        self.disTLArmAll_pushButton.setObjectName("disTLArmAll_pushButton")
        self.horizontalLayout_26.addWidget(self.disTLArmAll_pushButton)
        self.verticalLayout_7.addLayout(self.horizontalLayout_26)
        self.horizontalLayout_20 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_20.setObjectName("horizontalLayout_20")
        self.ID21_label = QtWidgets.QLabel(self.verticalLayoutWidget_7)
        self.ID21_label.setObjectName("ID21_label")
        self.horizontalLayout_20.addWidget(self.ID21_label)
        self.motorType21_label = QtWidgets.QLabel(self.verticalLayoutWidget_7)
        self.motorType21_label.setObjectName("motorType21_label")
        self.horizontalLayout_20.addWidget(self.motorType21_label)
        self.motor21center_label = QtWidgets.QLabel(self.verticalLayoutWidget_7)
        self.motor21center_label.setObjectName("motor21center_label")
        self.horizontalLayout_20.addWidget(self.motor21center_label)
        self.motor21Value_spinBox = QtWidgets.QSpinBox(self.verticalLayoutWidget_7)
        self.motor21Value_spinBox.setMaximum(4095)
        self.motor21Value_spinBox.setObjectName("motor21Value_spinBox")
        self.horizontalLayout_20.addWidget(self.motor21Value_spinBox)
        self.motor21value_dial = QtWidgets.QDial(self.verticalLayoutWidget_7)
        self.motor21value_dial.setMaximum(4095)
        self.motor21value_dial.setObjectName("motor21value_dial")
        self.horizontalLayout_20.addWidget(self.motor21value_dial)
        self.motor21Set_pushButton = QtWidgets.QPushButton(self.verticalLayoutWidget_7)
        self.motor21Set_pushButton.setObjectName("motor21Set_pushButton")
        self.horizontalLayout_20.addWidget(self.motor21Set_pushButton)
        self.motor21Get_pushButton = QtWidgets.QPushButton(self.verticalLayoutWidget_7)
        self.motor21Get_pushButton.setObjectName("motor21Get_pushButton")
        self.horizontalLayout_20.addWidget(self.motor21Get_pushButton)
        self.motor21DisT_pushButton = QtWidgets.QPushButton(self.verticalLayoutWidget_7)
        self.motor21DisT_pushButton.setObjectName("motor21DisT_pushButton")
        self.horizontalLayout_20.addWidget(self.motor21DisT_pushButton)
        self.verticalLayout_7.addLayout(self.horizontalLayout_20)
        self.horizontalLayout_21 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_21.setObjectName("horizontalLayout_21")
        self.ID22_label = QtWidgets.QLabel(self.verticalLayoutWidget_7)
        self.ID22_label.setObjectName("ID22_label")
        self.horizontalLayout_21.addWidget(self.ID22_label)
        self.motorType22_label = QtWidgets.QLabel(self.verticalLayoutWidget_7)
        self.motorType22_label.setObjectName("motorType22_label")
        self.horizontalLayout_21.addWidget(self.motorType22_label)
        self.motor22center_label = QtWidgets.QLabel(self.verticalLayoutWidget_7)
        self.motor22center_label.setObjectName("motor22center_label")
        self.horizontalLayout_21.addWidget(self.motor22center_label)
        self.motor22Value_spinBox = QtWidgets.QSpinBox(self.verticalLayoutWidget_7)
        self.motor22Value_spinBox.setMaximum(4095)
        self.motor22Value_spinBox.setObjectName("motor22Value_spinBox")
        self.horizontalLayout_21.addWidget(self.motor22Value_spinBox)
        self.motor22value_dial = QtWidgets.QDial(self.verticalLayoutWidget_7)
        self.motor22value_dial.setMaximum(4095)
        self.motor22value_dial.setObjectName("motor22value_dial")
        self.horizontalLayout_21.addWidget(self.motor22value_dial)
        self.motor22Set_pushButton = QtWidgets.QPushButton(self.verticalLayoutWidget_7)
        self.motor22Set_pushButton.setObjectName("motor22Set_pushButton")
        self.horizontalLayout_21.addWidget(self.motor22Set_pushButton)
        self.motor22Get_pushButton = QtWidgets.QPushButton(self.verticalLayoutWidget_7)
        self.motor22Get_pushButton.setObjectName("motor22Get_pushButton")
        self.horizontalLayout_21.addWidget(self.motor22Get_pushButton)
        self.motor22DisT_pushButton = QtWidgets.QPushButton(self.verticalLayoutWidget_7)
        self.motor22DisT_pushButton.setObjectName("motor22DisT_pushButton")
        self.horizontalLayout_21.addWidget(self.motor22DisT_pushButton)
        self.verticalLayout_7.addLayout(self.horizontalLayout_21)
        self.horizontalLayout_19 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_19.setObjectName("horizontalLayout_19")
        self.ID23_label = QtWidgets.QLabel(self.verticalLayoutWidget_7)
        self.ID23_label.setObjectName("ID23_label")
        self.horizontalLayout_19.addWidget(self.ID23_label)
        self.motorType23_label = QtWidgets.QLabel(self.verticalLayoutWidget_7)
        self.motorType23_label.setObjectName("motorType23_label")
        self.horizontalLayout_19.addWidget(self.motorType23_label)
        self.motor23center_label = QtWidgets.QLabel(self.verticalLayoutWidget_7)
        self.motor23center_label.setObjectName("motor23center_label")
        self.horizontalLayout_19.addWidget(self.motor23center_label)
        self.motor23Value_spinBox = QtWidgets.QSpinBox(self.verticalLayoutWidget_7)
        self.motor23Value_spinBox.setMaximum(4095)
        self.motor23Value_spinBox.setObjectName("motor23Value_spinBox")
        self.horizontalLayout_19.addWidget(self.motor23Value_spinBox)
        self.motor23value_dial = QtWidgets.QDial(self.verticalLayoutWidget_7)
        self.motor23value_dial.setMaximum(4095)
        self.motor23value_dial.setObjectName("motor23value_dial")
        self.horizontalLayout_19.addWidget(self.motor23value_dial)
        self.motor23Set_pushButton = QtWidgets.QPushButton(self.verticalLayoutWidget_7)
        self.motor23Set_pushButton.setObjectName("motor23Set_pushButton")
        self.horizontalLayout_19.addWidget(self.motor23Set_pushButton)
        self.motor23Get_pushButton = QtWidgets.QPushButton(self.verticalLayoutWidget_7)
        self.motor23Get_pushButton.setObjectName("motor23Get_pushButton")
        self.horizontalLayout_19.addWidget(self.motor23Get_pushButton)
        self.motor23DisT_pushButton = QtWidgets.QPushButton(self.verticalLayoutWidget_7)
        self.motor23DisT_pushButton.setObjectName("motor23DisT_pushButton")
        self.horizontalLayout_19.addWidget(self.motor23DisT_pushButton)
        self.verticalLayout_7.addLayout(self.horizontalLayout_19)
        self.horizontalLayout_27 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_27.setObjectName("horizontalLayout_27")
        self.ID24_label = QtWidgets.QLabel(self.verticalLayoutWidget_7)
        self.ID24_label.setObjectName("ID24_label")
        self.horizontalLayout_27.addWidget(self.ID24_label)
        self.motorType24_label = QtWidgets.QLabel(self.verticalLayoutWidget_7)
        self.motorType24_label.setObjectName("motorType24_label")
        self.horizontalLayout_27.addWidget(self.motorType24_label)
        self.motor24center_label = QtWidgets.QLabel(self.verticalLayoutWidget_7)
        self.motor24center_label.setObjectName("motor24center_label")
        self.horizontalLayout_27.addWidget(self.motor24center_label)
        self.motor24Value_spinBox = QtWidgets.QSpinBox(self.verticalLayoutWidget_7)
        self.motor24Value_spinBox.setMaximum(4095)
        self.motor24Value_spinBox.setObjectName("motor24Value_spinBox")
        self.horizontalLayout_27.addWidget(self.motor24Value_spinBox)
        self.motor24value_dial = QtWidgets.QDial(self.verticalLayoutWidget_7)
        self.motor24value_dial.setMaximum(4095)
        self.motor24value_dial.setObjectName("motor24value_dial")
        self.horizontalLayout_27.addWidget(self.motor24value_dial)
        self.motor24Set_pushButton = QtWidgets.QPushButton(self.verticalLayoutWidget_7)
        self.motor24Set_pushButton.setObjectName("motor24Set_pushButton")
        self.horizontalLayout_27.addWidget(self.motor24Set_pushButton)
        self.motor24Get_pushButton = QtWidgets.QPushButton(self.verticalLayoutWidget_7)
        self.motor24Get_pushButton.setObjectName("motor24Get_pushButton")
        self.horizontalLayout_27.addWidget(self.motor24Get_pushButton)
        self.motor24DisT_pushButton = QtWidgets.QPushButton(self.verticalLayoutWidget_7)
        self.motor24DisT_pushButton.setObjectName("motor24DisT_pushButton")
        self.horizontalLayout_27.addWidget(self.motor24DisT_pushButton)
        self.verticalLayout_7.addLayout(self.horizontalLayout_27)
        self.layoutWidget = QtWidgets.QWidget(Form)
        self.layoutWidget.setGeometry(QtCore.QRect(500, 250, 471, 291))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.horizontalLayout_25 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_25.setObjectName("horizontalLayout_25")
        self.setRAll_pushButton = QtWidgets.QPushButton(self.layoutWidget)
        self.setRAll_pushButton.setObjectName("setRAll_pushButton")
        self.horizontalLayout_25.addWidget(self.setRAll_pushButton)
        self.getRAll_pushButton = QtWidgets.QPushButton(self.layoutWidget)
        self.getRAll_pushButton.setObjectName("getRAll_pushButton")
        self.horizontalLayout_25.addWidget(self.getRAll_pushButton)
        self.disTRAll_pushButton = QtWidgets.QPushButton(self.layoutWidget)
        self.disTRAll_pushButton.setObjectName("disTRAll_pushButton")
        self.horizontalLayout_25.addWidget(self.disTRAll_pushButton)
        self.verticalLayout_6.addLayout(self.horizontalLayout_25)
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.ID11_label = QtWidgets.QLabel(self.layoutWidget)
        self.ID11_label.setObjectName("ID11_label")
        self.horizontalLayout_12.addWidget(self.ID11_label)
        self.motorType11_label = QtWidgets.QLabel(self.layoutWidget)
        self.motorType11_label.setObjectName("motorType11_label")
        self.horizontalLayout_12.addWidget(self.motorType11_label)
        self.motor11center_label = QtWidgets.QLabel(self.layoutWidget)
        self.motor11center_label.setObjectName("motor11center_label")
        self.horizontalLayout_12.addWidget(self.motor11center_label)
        self.motor11Value_spinBox = QtWidgets.QSpinBox(self.layoutWidget)
        self.motor11Value_spinBox.setMaximum(4095)
        self.motor11Value_spinBox.setObjectName("motor11Value_spinBox")
        self.horizontalLayout_12.addWidget(self.motor11Value_spinBox)
        self.motor11value_dial = QtWidgets.QDial(self.layoutWidget)
        self.motor11value_dial.setMaximum(4095)
        self.motor11value_dial.setObjectName("motor11value_dial")
        self.horizontalLayout_12.addWidget(self.motor11value_dial)
        self.motor11Set_pushButton = QtWidgets.QPushButton(self.layoutWidget)
        self.motor11Set_pushButton.setObjectName("motor11Set_pushButton")
        self.horizontalLayout_12.addWidget(self.motor11Set_pushButton)
        self.motor11Get_pushButton = QtWidgets.QPushButton(self.layoutWidget)
        self.motor11Get_pushButton.setObjectName("motor11Get_pushButton")
        self.horizontalLayout_12.addWidget(self.motor11Get_pushButton)
        self.motor11DisT_pushButton = QtWidgets.QPushButton(self.layoutWidget)
        self.motor11DisT_pushButton.setObjectName("motor11DisT_pushButton")
        self.horizontalLayout_12.addWidget(self.motor11DisT_pushButton)
        self.verticalLayout_6.addLayout(self.horizontalLayout_12)
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.ID12_label = QtWidgets.QLabel(self.layoutWidget)
        self.ID12_label.setObjectName("ID12_label")
        self.horizontalLayout_13.addWidget(self.ID12_label)
        self.motorType12_label = QtWidgets.QLabel(self.layoutWidget)
        self.motorType12_label.setObjectName("motorType12_label")
        self.horizontalLayout_13.addWidget(self.motorType12_label)
        self.motor12center_label = QtWidgets.QLabel(self.layoutWidget)
        self.motor12center_label.setObjectName("motor12center_label")
        self.horizontalLayout_13.addWidget(self.motor12center_label)
        self.motor12Value_spinBox = QtWidgets.QSpinBox(self.layoutWidget)
        self.motor12Value_spinBox.setMaximum(4095)
        self.motor12Value_spinBox.setObjectName("motor12Value_spinBox")
        self.horizontalLayout_13.addWidget(self.motor12Value_spinBox)
        self.motor12value_dial = QtWidgets.QDial(self.layoutWidget)
        self.motor12value_dial.setMaximum(4095)
        self.motor12value_dial.setObjectName("motor12value_dial")
        self.horizontalLayout_13.addWidget(self.motor12value_dial)
        self.motor12Set_pushButton = QtWidgets.QPushButton(self.layoutWidget)
        self.motor12Set_pushButton.setObjectName("motor12Set_pushButton")
        self.horizontalLayout_13.addWidget(self.motor12Set_pushButton)
        self.motor12Get_pushButton = QtWidgets.QPushButton(self.layoutWidget)
        self.motor12Get_pushButton.setObjectName("motor12Get_pushButton")
        self.horizontalLayout_13.addWidget(self.motor12Get_pushButton)
        self.motor12DisT_pushButton = QtWidgets.QPushButton(self.layoutWidget)
        self.motor12DisT_pushButton.setObjectName("motor12DisT_pushButton")
        self.horizontalLayout_13.addWidget(self.motor12DisT_pushButton)
        self.verticalLayout_6.addLayout(self.horizontalLayout_13)
        self.horizontalLayout_14 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_14.setObjectName("horizontalLayout_14")
        self.ID13_label = QtWidgets.QLabel(self.layoutWidget)
        self.ID13_label.setObjectName("ID13_label")
        self.horizontalLayout_14.addWidget(self.ID13_label)
        self.motorType13_label = QtWidgets.QLabel(self.layoutWidget)
        self.motorType13_label.setObjectName("motorType13_label")
        self.horizontalLayout_14.addWidget(self.motorType13_label)
        self.motor13center_label = QtWidgets.QLabel(self.layoutWidget)
        self.motor13center_label.setObjectName("motor13center_label")
        self.horizontalLayout_14.addWidget(self.motor13center_label)
        self.motor13Value_spinBox = QtWidgets.QSpinBox(self.layoutWidget)
        self.motor13Value_spinBox.setMaximum(4095)
        self.motor13Value_spinBox.setObjectName("motor13Value_spinBox")
        self.horizontalLayout_14.addWidget(self.motor13Value_spinBox)
        self.motor13value_dial = QtWidgets.QDial(self.layoutWidget)
        self.motor13value_dial.setMaximum(4095)
        self.motor13value_dial.setObjectName("motor13value_dial")
        self.horizontalLayout_14.addWidget(self.motor13value_dial)
        self.motor13Set_pushButton = QtWidgets.QPushButton(self.layoutWidget)
        self.motor13Set_pushButton.setObjectName("motor13Set_pushButton")
        self.horizontalLayout_14.addWidget(self.motor13Set_pushButton)
        self.motor13Get_pushButton = QtWidgets.QPushButton(self.layoutWidget)
        self.motor13Get_pushButton.setObjectName("motor13Get_pushButton")
        self.horizontalLayout_14.addWidget(self.motor13Get_pushButton)
        self.motor13DisT_pushButton = QtWidgets.QPushButton(self.layoutWidget)
        self.motor13DisT_pushButton.setObjectName("motor13DisT_pushButton")
        self.horizontalLayout_14.addWidget(self.motor13DisT_pushButton)
        self.verticalLayout_6.addLayout(self.horizontalLayout_14)
        self.horizontalLayout_15 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_15.setObjectName("horizontalLayout_15")
        self.ID14_label = QtWidgets.QLabel(self.layoutWidget)
        self.ID14_label.setObjectName("ID14_label")
        self.horizontalLayout_15.addWidget(self.ID14_label)
        self.motorType14_label = QtWidgets.QLabel(self.layoutWidget)
        self.motorType14_label.setObjectName("motorType14_label")
        self.horizontalLayout_15.addWidget(self.motorType14_label)
        self.motor14center_label = QtWidgets.QLabel(self.layoutWidget)
        self.motor14center_label.setObjectName("motor14center_label")
        self.horizontalLayout_15.addWidget(self.motor14center_label)
        self.motor14Value_spinBox = QtWidgets.QSpinBox(self.layoutWidget)
        self.motor14Value_spinBox.setMaximum(4095)
        self.motor14Value_spinBox.setObjectName("motor14Value_spinBox")
        self.horizontalLayout_15.addWidget(self.motor14Value_spinBox)
        self.motor14value_dial = QtWidgets.QDial(self.layoutWidget)
        self.motor14value_dial.setMaximum(4095)
        self.motor14value_dial.setObjectName("motor14value_dial")
        self.horizontalLayout_15.addWidget(self.motor14value_dial)
        self.motor14Set_pushButton = QtWidgets.QPushButton(self.layoutWidget)
        self.motor14Set_pushButton.setObjectName("motor14Set_pushButton")
        self.horizontalLayout_15.addWidget(self.motor14Set_pushButton)
        self.motor14Get_pushButton = QtWidgets.QPushButton(self.layoutWidget)
        self.motor14Get_pushButton.setObjectName("motor14Get_pushButton")
        self.horizontalLayout_15.addWidget(self.motor14Get_pushButton)
        self.motor14DisT_pushButton = QtWidgets.QPushButton(self.layoutWidget)
        self.motor14DisT_pushButton.setObjectName("motor14DisT_pushButton")
        self.horizontalLayout_15.addWidget(self.motor14DisT_pushButton)
        self.verticalLayout_6.addLayout(self.horizontalLayout_15)
        self.horizontalLayout_16 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_16.setObjectName("horizontalLayout_16")
        self.ID15_label = QtWidgets.QLabel(self.layoutWidget)
        self.ID15_label.setObjectName("ID15_label")
        self.horizontalLayout_16.addWidget(self.ID15_label)
        self.motorType15_label = QtWidgets.QLabel(self.layoutWidget)
        self.motorType15_label.setObjectName("motorType15_label")
        self.horizontalLayout_16.addWidget(self.motorType15_label)
        self.motor15center_label = QtWidgets.QLabel(self.layoutWidget)
        self.motor15center_label.setObjectName("motor15center_label")
        self.horizontalLayout_16.addWidget(self.motor15center_label)
        self.motor15Value_spinBox = QtWidgets.QSpinBox(self.layoutWidget)
        self.motor15Value_spinBox.setMaximum(4095)
        self.motor15Value_spinBox.setObjectName("motor15Value_spinBox")
        self.horizontalLayout_16.addWidget(self.motor15Value_spinBox)
        self.motor15value_dial = QtWidgets.QDial(self.layoutWidget)
        self.motor15value_dial.setMaximum(4095)
        self.motor15value_dial.setObjectName("motor15value_dial")
        self.horizontalLayout_16.addWidget(self.motor15value_dial)
        self.motor15Set_pushButton = QtWidgets.QPushButton(self.layoutWidget)
        self.motor15Set_pushButton.setObjectName("motor15Set_pushButton")
        self.horizontalLayout_16.addWidget(self.motor15Set_pushButton)
        self.motor15Get_pushButton = QtWidgets.QPushButton(self.layoutWidget)
        self.motor15Get_pushButton.setObjectName("motor15Get_pushButton")
        self.horizontalLayout_16.addWidget(self.motor15Get_pushButton)
        self.motor15DisT_pushButton = QtWidgets.QPushButton(self.layoutWidget)
        self.motor15DisT_pushButton.setObjectName("motor15DisT_pushButton")
        self.horizontalLayout_16.addWidget(self.motor15DisT_pushButton)
        self.verticalLayout_6.addLayout(self.horizontalLayout_16)
        self.horizontalLayout_17 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_17.setObjectName("horizontalLayout_17")
        self.ID7_label_ = QtWidgets.QLabel(self.layoutWidget)
        self.ID7_label_.setObjectName("ID7_label_")
        self.horizontalLayout_17.addWidget(self.ID7_label_)
        self.motorType16_label = QtWidgets.QLabel(self.layoutWidget)
        self.motorType16_label.setObjectName("motorType16_label")
        self.horizontalLayout_17.addWidget(self.motorType16_label)
        self.motor16center_label = QtWidgets.QLabel(self.layoutWidget)
        self.motor16center_label.setObjectName("motor16center_label")
        self.horizontalLayout_17.addWidget(self.motor16center_label)
        self.motor16Value_spinBox = QtWidgets.QSpinBox(self.layoutWidget)
        self.motor16Value_spinBox.setMaximum(4095)
        self.motor16Value_spinBox.setObjectName("motor16Value_spinBox")
        self.horizontalLayout_17.addWidget(self.motor16Value_spinBox)
        self.motor16value_dial = QtWidgets.QDial(self.layoutWidget)
        self.motor16value_dial.setMaximum(4095)
        self.motor16value_dial.setObjectName("motor16value_dial")
        self.horizontalLayout_17.addWidget(self.motor16value_dial)
        self.motor16Set_pushButton = QtWidgets.QPushButton(self.layoutWidget)
        self.motor16Set_pushButton.setObjectName("motor16Set_pushButton")
        self.horizontalLayout_17.addWidget(self.motor16Set_pushButton)
        self.motor16Get_pushButton = QtWidgets.QPushButton(self.layoutWidget)
        self.motor16Get_pushButton.setObjectName("motor16Get_pushButton")
        self.horizontalLayout_17.addWidget(self.motor16Get_pushButton)
        self.motor16DisT_pushButton = QtWidgets.QPushButton(self.layoutWidget)
        self.motor16DisT_pushButton.setObjectName("motor16DisT_pushButton")
        self.horizontalLayout_17.addWidget(self.motor16DisT_pushButton)
        self.verticalLayout_6.addLayout(self.horizontalLayout_17)
        self.layoutWidget1 = QtWidgets.QWidget(Form)
        self.layoutWidget1.setGeometry(QtCore.QRect(10, 250, 471, 291))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.layoutWidget1)
        self.verticalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.horizontalLayout_22 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_22.setObjectName("horizontalLayout_22")
        self.setLAll_pushButton = QtWidgets.QPushButton(self.layoutWidget1)
        self.setLAll_pushButton.setObjectName("setLAll_pushButton")
        self.horizontalLayout_22.addWidget(self.setLAll_pushButton)
        self.getLAll_pushButton = QtWidgets.QPushButton(self.layoutWidget1)
        self.getLAll_pushButton.setObjectName("getLAll_pushButton")
        self.horizontalLayout_22.addWidget(self.getLAll_pushButton)
        self.disTLAll_pushButton = QtWidgets.QPushButton(self.layoutWidget1)
        self.disTLAll_pushButton.setObjectName("disTLAll_pushButton")
        self.horizontalLayout_22.addWidget(self.disTLAll_pushButton)
        self.verticalLayout_5.addLayout(self.horizontalLayout_22)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.ID1_label = QtWidgets.QLabel(self.layoutWidget1)
        self.ID1_label.setObjectName("ID1_label")
        self.horizontalLayout_4.addWidget(self.ID1_label)
        self.motorType1_label = QtWidgets.QLabel(self.layoutWidget1)
        self.motorType1_label.setObjectName("motorType1_label")
        self.horizontalLayout_4.addWidget(self.motorType1_label)
        self.motor1center_label = QtWidgets.QLabel(self.layoutWidget1)
        self.motor1center_label.setObjectName("motor1center_label")
        self.horizontalLayout_4.addWidget(self.motor1center_label)
        self.motor1Value_spinBox = QtWidgets.QSpinBox(self.layoutWidget1)
        self.motor1Value_spinBox.setMaximum(4095)
        self.motor1Value_spinBox.setObjectName("motor1Value_spinBox")
        self.horizontalLayout_4.addWidget(self.motor1Value_spinBox)
        self.motor1value_dial = QtWidgets.QDial(self.layoutWidget1)
        self.motor1value_dial.setMaximum(4095)
        self.motor1value_dial.setObjectName("motor1value_dial")
        self.horizontalLayout_4.addWidget(self.motor1value_dial)
        self.motor1Set_pushButton = QtWidgets.QPushButton(self.layoutWidget1)
        self.motor1Set_pushButton.setObjectName("motor1Set_pushButton")
        self.horizontalLayout_4.addWidget(self.motor1Set_pushButton)
        self.motor1Get_pushButton = QtWidgets.QPushButton(self.layoutWidget1)
        self.motor1Get_pushButton.setObjectName("motor1Get_pushButton")
        self.horizontalLayout_4.addWidget(self.motor1Get_pushButton)
        self.motor1DisT_pushButton = QtWidgets.QPushButton(self.layoutWidget1)
        self.motor1DisT_pushButton.setObjectName("motor1DisT_pushButton")
        self.horizontalLayout_4.addWidget(self.motor1DisT_pushButton)
        self.verticalLayout_5.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.ID2_label = QtWidgets.QLabel(self.layoutWidget1)
        self.ID2_label.setObjectName("ID2_label")
        self.horizontalLayout_5.addWidget(self.ID2_label)
        self.motorType2_label = QtWidgets.QLabel(self.layoutWidget1)
        self.motorType2_label.setObjectName("motorType2_label")
        self.horizontalLayout_5.addWidget(self.motorType2_label)
        self.motor2center_label = QtWidgets.QLabel(self.layoutWidget1)
        self.motor2center_label.setObjectName("motor2center_label")
        self.horizontalLayout_5.addWidget(self.motor2center_label)
        self.motor2Value_spinBox = QtWidgets.QSpinBox(self.layoutWidget1)
        self.motor2Value_spinBox.setMaximum(4095)
        self.motor2Value_spinBox.setObjectName("motor2Value_spinBox")
        self.horizontalLayout_5.addWidget(self.motor2Value_spinBox)
        self.motor2value_dial = QtWidgets.QDial(self.layoutWidget1)
        self.motor2value_dial.setMaximum(4095)
        self.motor2value_dial.setObjectName("motor2value_dial")
        self.horizontalLayout_5.addWidget(self.motor2value_dial)
        self.motor2Set_pushButton = QtWidgets.QPushButton(self.layoutWidget1)
        self.motor2Set_pushButton.setObjectName("motor2Set_pushButton")
        self.horizontalLayout_5.addWidget(self.motor2Set_pushButton)
        self.motor2Get_pushButton = QtWidgets.QPushButton(self.layoutWidget1)
        self.motor2Get_pushButton.setObjectName("motor2Get_pushButton")
        self.horizontalLayout_5.addWidget(self.motor2Get_pushButton)
        self.motor2DisT_pushButton = QtWidgets.QPushButton(self.layoutWidget1)
        self.motor2DisT_pushButton.setObjectName("motor2DisT_pushButton")
        self.horizontalLayout_5.addWidget(self.motor2DisT_pushButton)
        self.verticalLayout_5.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.ID3_label = QtWidgets.QLabel(self.layoutWidget1)
        self.ID3_label.setObjectName("ID3_label")
        self.horizontalLayout_6.addWidget(self.ID3_label)
        self.motorType3_label = QtWidgets.QLabel(self.layoutWidget1)
        self.motorType3_label.setObjectName("motorType3_label")
        self.horizontalLayout_6.addWidget(self.motorType3_label)
        self.motor3center_label = QtWidgets.QLabel(self.layoutWidget1)
        self.motor3center_label.setObjectName("motor3center_label")
        self.horizontalLayout_6.addWidget(self.motor3center_label)
        self.motor3Value_spinBox = QtWidgets.QSpinBox(self.layoutWidget1)
        self.motor3Value_spinBox.setMaximum(4095)
        self.motor3Value_spinBox.setObjectName("motor3Value_spinBox")
        self.horizontalLayout_6.addWidget(self.motor3Value_spinBox)
        self.motor3value_dial = QtWidgets.QDial(self.layoutWidget1)
        self.motor3value_dial.setMaximum(4095)
        self.motor3value_dial.setObjectName("motor3value_dial")
        self.horizontalLayout_6.addWidget(self.motor3value_dial)
        self.motor3Set_pushButton = QtWidgets.QPushButton(self.layoutWidget1)
        self.motor3Set_pushButton.setObjectName("motor3Set_pushButton")
        self.horizontalLayout_6.addWidget(self.motor3Set_pushButton)
        self.motor3Get_pushButton = QtWidgets.QPushButton(self.layoutWidget1)
        self.motor3Get_pushButton.setObjectName("motor3Get_pushButton")
        self.horizontalLayout_6.addWidget(self.motor3Get_pushButton)
        self.motor3DisT_pushButton = QtWidgets.QPushButton(self.layoutWidget1)
        self.motor3DisT_pushButton.setObjectName("motor3DisT_pushButton")
        self.horizontalLayout_6.addWidget(self.motor3DisT_pushButton)
        self.verticalLayout_5.addLayout(self.horizontalLayout_6)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.ID4_label = QtWidgets.QLabel(self.layoutWidget1)
        self.ID4_label.setObjectName("ID4_label")
        self.horizontalLayout_7.addWidget(self.ID4_label)
        self.motorType4_label = QtWidgets.QLabel(self.layoutWidget1)
        self.motorType4_label.setObjectName("motorType4_label")
        self.horizontalLayout_7.addWidget(self.motorType4_label)
        self.motor4center_label = QtWidgets.QLabel(self.layoutWidget1)
        self.motor4center_label.setObjectName("motor4center_label")
        self.horizontalLayout_7.addWidget(self.motor4center_label)
        self.motor4Value_spinBox = QtWidgets.QSpinBox(self.layoutWidget1)
        self.motor4Value_spinBox.setMaximum(4095)
        self.motor4Value_spinBox.setObjectName("motor4Value_spinBox")
        self.horizontalLayout_7.addWidget(self.motor4Value_spinBox)
        self.motor4value_dial = QtWidgets.QDial(self.layoutWidget1)
        self.motor4value_dial.setMaximum(4095)
        self.motor4value_dial.setObjectName("motor4value_dial")
        self.horizontalLayout_7.addWidget(self.motor4value_dial)
        self.motor4Set_pushButton = QtWidgets.QPushButton(self.layoutWidget1)
        self.motor4Set_pushButton.setObjectName("motor4Set_pushButton")
        self.horizontalLayout_7.addWidget(self.motor4Set_pushButton)
        self.motor4Get_pushButton = QtWidgets.QPushButton(self.layoutWidget1)
        self.motor4Get_pushButton.setObjectName("motor4Get_pushButton")
        self.horizontalLayout_7.addWidget(self.motor4Get_pushButton)
        self.motor4DisT_pushButton = QtWidgets.QPushButton(self.layoutWidget1)
        self.motor4DisT_pushButton.setObjectName("motor4DisT_pushButton")
        self.horizontalLayout_7.addWidget(self.motor4DisT_pushButton)
        self.verticalLayout_5.addLayout(self.horizontalLayout_7)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.ID5_label = QtWidgets.QLabel(self.layoutWidget1)
        self.ID5_label.setObjectName("ID5_label")
        self.horizontalLayout_8.addWidget(self.ID5_label)
        self.motorType5_label = QtWidgets.QLabel(self.layoutWidget1)
        self.motorType5_label.setObjectName("motorType5_label")
        self.horizontalLayout_8.addWidget(self.motorType5_label)
        self.motor5center_label = QtWidgets.QLabel(self.layoutWidget1)
        self.motor5center_label.setObjectName("motor5center_label")
        self.horizontalLayout_8.addWidget(self.motor5center_label)
        self.motor5Value_spinBox = QtWidgets.QSpinBox(self.layoutWidget1)
        self.motor5Value_spinBox.setMaximum(4095)
        self.motor5Value_spinBox.setObjectName("motor5Value_spinBox")
        self.horizontalLayout_8.addWidget(self.motor5Value_spinBox)
        self.motor5value_dial = QtWidgets.QDial(self.layoutWidget1)
        self.motor5value_dial.setMaximum(4095)
        self.motor5value_dial.setObjectName("motor5value_dial")
        self.horizontalLayout_8.addWidget(self.motor5value_dial)
        self.motor5Set_pushButton = QtWidgets.QPushButton(self.layoutWidget1)
        self.motor5Set_pushButton.setObjectName("motor5Set_pushButton")
        self.horizontalLayout_8.addWidget(self.motor5Set_pushButton)
        self.motor5Get_pushButton = QtWidgets.QPushButton(self.layoutWidget1)
        self.motor5Get_pushButton.setObjectName("motor5Get_pushButton")
        self.horizontalLayout_8.addWidget(self.motor5Get_pushButton)
        self.motor5DisT_pushButton = QtWidgets.QPushButton(self.layoutWidget1)
        self.motor5DisT_pushButton.setObjectName("motor5DisT_pushButton")
        self.horizontalLayout_8.addWidget(self.motor5DisT_pushButton)
        self.verticalLayout_5.addLayout(self.horizontalLayout_8)
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.ID6_label = QtWidgets.QLabel(self.layoutWidget1)
        self.ID6_label.setObjectName("ID6_label")
        self.horizontalLayout_9.addWidget(self.ID6_label)
        self.motorType6_label = QtWidgets.QLabel(self.layoutWidget1)
        self.motorType6_label.setObjectName("motorType6_label")
        self.horizontalLayout_9.addWidget(self.motorType6_label)
        self.motor6center_label = QtWidgets.QLabel(self.layoutWidget1)
        self.motor6center_label.setObjectName("motor6center_label")
        self.horizontalLayout_9.addWidget(self.motor6center_label)
        self.motor6Value_spinBox = QtWidgets.QSpinBox(self.layoutWidget1)
        self.motor6Value_spinBox.setMaximum(4095)
        self.motor6Value_spinBox.setObjectName("motor6Value_spinBox")
        self.horizontalLayout_9.addWidget(self.motor6Value_spinBox)
        self.motor6value_dial = QtWidgets.QDial(self.layoutWidget1)
        self.motor6value_dial.setMaximum(4095)
        self.motor6value_dial.setObjectName("motor6value_dial")
        self.horizontalLayout_9.addWidget(self.motor6value_dial)
        self.motor6Set_pushButton = QtWidgets.QPushButton(self.layoutWidget1)
        self.motor6Set_pushButton.setObjectName("motor6Set_pushButton")
        self.horizontalLayout_9.addWidget(self.motor6Set_pushButton)
        self.motor6Get_pushButton = QtWidgets.QPushButton(self.layoutWidget1)
        self.motor6Get_pushButton.setObjectName("motor6Get_pushButton")
        self.horizontalLayout_9.addWidget(self.motor6Get_pushButton)
        self.motor6DisT_pushButton = QtWidgets.QPushButton(self.layoutWidget1)
        self.motor6DisT_pushButton.setObjectName("motor6DisT_pushButton")
        self.horizontalLayout_9.addWidget(self.motor6DisT_pushButton)
        self.verticalLayout_5.addLayout(self.horizontalLayout_9)
        self.layoutWidget2 = QtWidgets.QWidget(Form)
        self.layoutWidget2.setGeometry(QtCore.QRect(10, 120, 471, 31))
        self.layoutWidget2.setObjectName("layoutWidget2")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.layoutWidget2)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.play_label = QtWidgets.QLabel(self.layoutWidget2)
        self.play_label.setObjectName("play_label")
        self.verticalLayout.addWidget(self.play_label)
        self.horizontalLayout.addLayout(self.verticalLayout)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.allKeyframe_label = QtWidgets.QLabel(self.layoutWidget2)
        self.allKeyframe_label.setObjectName("allKeyframe_label")
        self.verticalLayout_2.addWidget(self.allKeyframe_label)
        self.horizontalLayout.addLayout(self.verticalLayout_2)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.setReady_Button = QtWidgets.QPushButton(self.layoutWidget2)
        self.setReady_Button.setObjectName("setReady_Button")
        self.verticalLayout_3.addWidget(self.setReady_Button)
        self.horizontalLayout.addLayout(self.verticalLayout_3)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.playAll_Button = QtWidgets.QPushButton(self.layoutWidget2)
        self.playAll_Button.setObjectName("playAll_Button")
        self.verticalLayout_4.addWidget(self.playAll_Button)
        self.horizontalLayout.addLayout(self.verticalLayout_4)
        self.layoutWidget3 = QtWidgets.QWidget(Form)
        self.layoutWidget3.setGeometry(QtCore.QRect(10, 150, 471, 31))
        self.layoutWidget3.setObjectName("layoutWidget3")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.layoutWidget3)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.SelectedKeyframe_label = QtWidgets.QLabel(self.layoutWidget3)
        self.SelectedKeyframe_label.setObjectName("SelectedKeyframe_label")
        self.horizontalLayout_2.addWidget(self.SelectedKeyframe_label)
        self.keyFrame_comboBox = QtWidgets.QComboBox(self.layoutWidget3)
        self.keyFrame_comboBox.setObjectName("keyFrame_comboBox")
        self.horizontalLayout_2.addWidget(self.keyFrame_comboBox)
        self.activeKeyframe_checkBox = QtWidgets.QCheckBox(self.layoutWidget3)
        self.activeKeyframe_checkBox.setEnabled(True)
        self.activeKeyframe_checkBox.setObjectName("activeKeyframe_checkBox")
        self.horizontalLayout_2.addWidget(self.activeKeyframe_checkBox)
        self.play_pushButton = QtWidgets.QPushButton(self.layoutWidget3)
        self.play_pushButton.setObjectName("play_pushButton")
        self.horizontalLayout_2.addWidget(self.play_pushButton)
        self.layoutWidget4 = QtWidgets.QWidget(Form)
        self.layoutWidget4.setGeometry(QtCore.QRect(10, 210, 471, 31))
        self.layoutWidget4.setObjectName("layoutWidget4")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.layoutWidget4)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.keyframeTime_label = QtWidgets.QLabel(self.layoutWidget4)
        self.keyframeTime_label.setObjectName("keyframeTime_label")
        self.horizontalLayout_3.addWidget(self.keyframeTime_label)
        self.keyframeTime_spinBox = QtWidgets.QSpinBox(self.layoutWidget4)
        self.keyframeTime_spinBox.setObjectName("keyframeTime_spinBox")
        self.horizontalLayout_3.addWidget(self.keyframeTime_spinBox)
        self.setTime_pushButton = QtWidgets.QPushButton(self.layoutWidget4)
        self.setTime_pushButton.setObjectName("setTime_pushButton")
        self.horizontalLayout_3.addWidget(self.setTime_pushButton)
        self.setAll_pushButton = QtWidgets.QPushButton(self.layoutWidget4)
        self.setAll_pushButton.setObjectName("setAll_pushButton")
        self.horizontalLayout_3.addWidget(self.setAll_pushButton)
        self.getAll_pushButton = QtWidgets.QPushButton(self.layoutWidget4)
        self.getAll_pushButton.setObjectName("getAll_pushButton")
        self.horizontalLayout_3.addWidget(self.getAll_pushButton)
        self.disTAll_pushButton = QtWidgets.QPushButton(self.layoutWidget4)
        self.disTAll_pushButton.setObjectName("disTAll_pushButton")
        self.horizontalLayout_3.addWidget(self.disTAll_pushButton)
        self.horizontalLayoutWidget_3 = QtWidgets.QWidget(Form)
        self.horizontalLayoutWidget_3.setGeometry(QtCore.QRect(500, 10, 471, 29))
        self.horizontalLayoutWidget_3.setObjectName("horizontalLayoutWidget_3")
        self.horizontalLayout_24 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_3)
        self.horizontalLayout_24.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_24.setObjectName("horizontalLayout_24")
        self.comport_comboBox = QtWidgets.QComboBox(self.horizontalLayoutWidget_3)
        self.comport_comboBox.setObjectName("comport_comboBox")
        self.horizontalLayout_24.addWidget(self.comport_comboBox)
        self.baudrate_comboBox = QtWidgets.QComboBox(self.horizontalLayoutWidget_3)
        self.baudrate_comboBox.setObjectName("baudrate_comboBox")
        self.horizontalLayout_24.addWidget(self.baudrate_comboBox)
        self.connectionStatus_label = QtWidgets.QLabel(self.horizontalLayoutWidget_3)
        self.connectionStatus_label.setObjectName("connectionStatus_label")
        self.horizontalLayout_24.addWidget(self.connectionStatus_label)
        self.connect_Button = QtWidgets.QPushButton(self.horizontalLayoutWidget_3)
        self.connect_Button.setObjectName("connect_Button")
        self.horizontalLayout_24.addWidget(self.connect_Button)
        self.horizontalLayoutWidget_2 = QtWidgets.QWidget(Form)
        self.horizontalLayoutWidget_2.setGeometry(QtCore.QRect(10, 90, 471, 29))
        self.horizontalLayoutWidget_2.setObjectName("horizontalLayoutWidget_2")
        self.horizontalLayout_23 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_2)
        self.horizontalLayout_23.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_23.setObjectName("horizontalLayout_23")
        self.postureSelect_label = QtWidgets.QLabel(self.horizontalLayoutWidget_2)
        self.postureSelect_label.setObjectName("postureSelect_label")
        self.horizontalLayout_23.addWidget(self.postureSelect_label)
        self.posture_comboBox = QtWidgets.QComboBox(self.horizontalLayoutWidget_2)
        self.posture_comboBox.setObjectName("posture_comboBox")
        self.horizontalLayout_23.addWidget(self.posture_comboBox)
        self.loadPosture_pushButton = QtWidgets.QPushButton(self.horizontalLayoutWidget_2)
        self.loadPosture_pushButton.setObjectName("loadPosture_pushButton")
        self.horizontalLayout_23.addWidget(self.loadPosture_pushButton)
        self.savePosture_pushButton = QtWidgets.QPushButton(self.horizontalLayoutWidget_2)
        self.savePosture_pushButton.setObjectName("savePosture_pushButton")
        self.horizontalLayout_23.addWidget(self.savePosture_pushButton)
        self.saveCenter_pushButton = QtWidgets.QPushButton(self.horizontalLayoutWidget_2)
        self.saveCenter_pushButton.setObjectName("saveCenter_pushButton")
        self.horizontalLayout_23.addWidget(self.saveCenter_pushButton)
        self.horizontalLayoutWidget = QtWidgets.QWidget(Form)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(10, 180, 471, 31))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout_18 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout_18.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_18.setObjectName("horizontalLayout_18")
        self.deleteKeyframe_pushButton = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.deleteKeyframe_pushButton.setObjectName("deleteKeyframe_pushButton")
        self.horizontalLayout_18.addWidget(self.deleteKeyframe_pushButton)
        self.duplicateKeyframe_pushButton = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.duplicateKeyframe_pushButton.setObjectName("duplicateKeyframe_pushButton")
        self.horizontalLayout_18.addWidget(self.duplicateKeyframe_pushButton)
        self.previousSwitchKeyframe_pushButton = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.previousSwitchKeyframe_pushButton.setObjectName("previousSwitchKeyframe_pushButton")
        self.horizontalLayout_18.addWidget(self.previousSwitchKeyframe_pushButton)
        self.nextSwitchKeyframe_pushButton = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.nextSwitchKeyframe_pushButton.setObjectName("nextSwitchKeyframe_pushButton")
        self.horizontalLayout_18.addWidget(self.nextSwitchKeyframe_pushButton)
        self.verticalLayoutWidget_8 = QtWidgets.QWidget(Form)
        self.verticalLayoutWidget_8.setGeometry(QtCore.QRect(500, 550, 471, 201))
        self.verticalLayoutWidget_8.setObjectName("verticalLayoutWidget_8")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_8)
        self.verticalLayout_8.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.horizontalLayout_28 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_28.setObjectName("horizontalLayout_28")
        self.setRArmAll_pushButton = QtWidgets.QPushButton(self.verticalLayoutWidget_8)
        self.setRArmAll_pushButton.setObjectName("setRArmAll_pushButton")
        self.horizontalLayout_28.addWidget(self.setRArmAll_pushButton)
        self.getRArmAll_pushButton = QtWidgets.QPushButton(self.verticalLayoutWidget_8)
        self.getRArmAll_pushButton.setObjectName("getRArmAll_pushButton")
        self.horizontalLayout_28.addWidget(self.getRArmAll_pushButton)
        self.disTRArmAll_pushButton = QtWidgets.QPushButton(self.verticalLayoutWidget_8)
        self.disTRArmAll_pushButton.setObjectName("disTRArmAll_pushButton")
        self.horizontalLayout_28.addWidget(self.disTRArmAll_pushButton)
        self.verticalLayout_8.addLayout(self.horizontalLayout_28)
        self.horizontalLayout_29 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_29.setObjectName("horizontalLayout_29")
        self.ID31_label = QtWidgets.QLabel(self.verticalLayoutWidget_8)
        self.ID31_label.setObjectName("ID31_label")
        self.horizontalLayout_29.addWidget(self.ID31_label)
        self.motorType31_label = QtWidgets.QLabel(self.verticalLayoutWidget_8)
        self.motorType31_label.setObjectName("motorType31_label")
        self.horizontalLayout_29.addWidget(self.motorType31_label)
        self.motor31center_label = QtWidgets.QLabel(self.verticalLayoutWidget_8)
        self.motor31center_label.setObjectName("motor31center_label")
        self.horizontalLayout_29.addWidget(self.motor31center_label)
        self.motor31Value_spinBox = QtWidgets.QSpinBox(self.verticalLayoutWidget_8)
        self.motor31Value_spinBox.setMaximum(4095)
        self.motor31Value_spinBox.setObjectName("motor31Value_spinBox")
        self.horizontalLayout_29.addWidget(self.motor31Value_spinBox)
        self.motor31value_dial = QtWidgets.QDial(self.verticalLayoutWidget_8)
        self.motor31value_dial.setMaximum(4095)
        self.motor31value_dial.setObjectName("motor31value_dial")
        self.horizontalLayout_29.addWidget(self.motor31value_dial)
        self.motor31Set_pushButton = QtWidgets.QPushButton(self.verticalLayoutWidget_8)
        self.motor31Set_pushButton.setObjectName("motor31Set_pushButton")
        self.horizontalLayout_29.addWidget(self.motor31Set_pushButton)
        self.motor31Get_pushButton = QtWidgets.QPushButton(self.verticalLayoutWidget_8)
        self.motor31Get_pushButton.setObjectName("motor31Get_pushButton")
        self.horizontalLayout_29.addWidget(self.motor31Get_pushButton)
        self.motor31DisT_pushButton = QtWidgets.QPushButton(self.verticalLayoutWidget_8)
        self.motor31DisT_pushButton.setObjectName("motor31DisT_pushButton")
        self.horizontalLayout_29.addWidget(self.motor31DisT_pushButton)
        self.verticalLayout_8.addLayout(self.horizontalLayout_29)
        self.horizontalLayout_30 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_30.setObjectName("horizontalLayout_30")
        self.ID32_label = QtWidgets.QLabel(self.verticalLayoutWidget_8)
        self.ID32_label.setObjectName("ID32_label")
        self.horizontalLayout_30.addWidget(self.ID32_label)
        self.motorType32_label = QtWidgets.QLabel(self.verticalLayoutWidget_8)
        self.motorType32_label.setObjectName("motorType32_label")
        self.horizontalLayout_30.addWidget(self.motorType32_label)
        self.motor32center_label = QtWidgets.QLabel(self.verticalLayoutWidget_8)
        self.motor32center_label.setObjectName("motor32center_label")
        self.horizontalLayout_30.addWidget(self.motor32center_label)
        self.motor32Value_spinBox = QtWidgets.QSpinBox(self.verticalLayoutWidget_8)
        self.motor32Value_spinBox.setMaximum(4095)
        self.motor32Value_spinBox.setObjectName("motor32Value_spinBox")
        self.horizontalLayout_30.addWidget(self.motor32Value_spinBox)
        self.motor32value_dial = QtWidgets.QDial(self.verticalLayoutWidget_8)
        self.motor32value_dial.setMaximum(4095)
        self.motor32value_dial.setObjectName("motor32value_dial")
        self.horizontalLayout_30.addWidget(self.motor32value_dial)
        self.motor32Set_pushButton = QtWidgets.QPushButton(self.verticalLayoutWidget_8)
        self.motor32Set_pushButton.setObjectName("motor32Set_pushButton")
        self.horizontalLayout_30.addWidget(self.motor32Set_pushButton)
        self.motor32Get_pushButton = QtWidgets.QPushButton(self.verticalLayoutWidget_8)
        self.motor32Get_pushButton.setObjectName("motor32Get_pushButton")
        self.horizontalLayout_30.addWidget(self.motor32Get_pushButton)
        self.motor32DisT_pushButton = QtWidgets.QPushButton(self.verticalLayoutWidget_8)
        self.motor32DisT_pushButton.setObjectName("motor32DisT_pushButton")
        self.horizontalLayout_30.addWidget(self.motor32DisT_pushButton)
        self.verticalLayout_8.addLayout(self.horizontalLayout_30)
        self.horizontalLayout_31 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_31.setObjectName("horizontalLayout_31")
        self.ID33_label = QtWidgets.QLabel(self.verticalLayoutWidget_8)
        self.ID33_label.setObjectName("ID33_label")
        self.horizontalLayout_31.addWidget(self.ID33_label)
        self.motorType33_label = QtWidgets.QLabel(self.verticalLayoutWidget_8)
        self.motorType33_label.setObjectName("motorType33_label")
        self.horizontalLayout_31.addWidget(self.motorType33_label)
        self.motor33center_label = QtWidgets.QLabel(self.verticalLayoutWidget_8)
        self.motor33center_label.setObjectName("motor33center_label")
        self.horizontalLayout_31.addWidget(self.motor33center_label)
        self.motor33Value_spinBox = QtWidgets.QSpinBox(self.verticalLayoutWidget_8)
        self.motor33Value_spinBox.setMaximum(4095)
        self.motor33Value_spinBox.setObjectName("motor33Value_spinBox")
        self.horizontalLayout_31.addWidget(self.motor33Value_spinBox)
        self.motor33value_dial = QtWidgets.QDial(self.verticalLayoutWidget_8)
        self.motor33value_dial.setMaximum(4095)
        self.motor33value_dial.setObjectName("motor33value_dial")
        self.horizontalLayout_31.addWidget(self.motor33value_dial)
        self.motor33Set_pushButton = QtWidgets.QPushButton(self.verticalLayoutWidget_8)
        self.motor33Set_pushButton.setObjectName("motor33Set_pushButton")
        self.horizontalLayout_31.addWidget(self.motor33Set_pushButton)
        self.motor33Get_pushButton = QtWidgets.QPushButton(self.verticalLayoutWidget_8)
        self.motor33Get_pushButton.setObjectName("motor33Get_pushButton")
        self.horizontalLayout_31.addWidget(self.motor33Get_pushButton)
        self.motor33DisT_pushButton = QtWidgets.QPushButton(self.verticalLayoutWidget_8)
        self.motor33DisT_pushButton.setObjectName("motor33DisT_pushButton")
        self.horizontalLayout_31.addWidget(self.motor33DisT_pushButton)
        self.verticalLayout_8.addLayout(self.horizontalLayout_31)
        self.horizontalLayout_32 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_32.setObjectName("horizontalLayout_32")
        self.ID34_label = QtWidgets.QLabel(self.verticalLayoutWidget_8)
        self.ID34_label.setObjectName("ID34_label")
        self.horizontalLayout_32.addWidget(self.ID34_label)
        self.motorType34_label = QtWidgets.QLabel(self.verticalLayoutWidget_8)
        self.motorType34_label.setObjectName("motorType34_label")
        self.horizontalLayout_32.addWidget(self.motorType34_label)
        self.motor34center_label = QtWidgets.QLabel(self.verticalLayoutWidget_8)
        self.motor34center_label.setObjectName("motor34center_label")
        self.horizontalLayout_32.addWidget(self.motor34center_label)
        self.motor34Value_spinBox = QtWidgets.QSpinBox(self.verticalLayoutWidget_8)
        self.motor34Value_spinBox.setMaximum(4095)
        self.motor34Value_spinBox.setObjectName("motor34Value_spinBox")
        self.horizontalLayout_32.addWidget(self.motor34Value_spinBox)
        self.motor34value_dial = QtWidgets.QDial(self.verticalLayoutWidget_8)
        self.motor34value_dial.setMaximum(4095)
        self.motor34value_dial.setObjectName("motor34value_dial")
        self.horizontalLayout_32.addWidget(self.motor34value_dial)
        self.motor34Set_pushButton = QtWidgets.QPushButton(self.verticalLayoutWidget_8)
        self.motor34Set_pushButton.setObjectName("motor34Set_pushButton")
        self.horizontalLayout_32.addWidget(self.motor34Set_pushButton)
        self.motor34Get_pushButton = QtWidgets.QPushButton(self.verticalLayoutWidget_8)
        self.motor34Get_pushButton.setObjectName("motor34Get_pushButton")
        self.horizontalLayout_32.addWidget(self.motor34Get_pushButton)
        self.motor34DisT_pushButton = QtWidgets.QPushButton(self.verticalLayoutWidget_8)
        self.motor34DisT_pushButton.setObjectName("motor34DisT_pushButton")
        self.horizontalLayout_32.addWidget(self.motor34DisT_pushButton)
        self.verticalLayout_8.addLayout(self.horizontalLayout_32)
        self.verticalLayoutWidget_9 = QtWidgets.QWidget(Form)
        self.verticalLayoutWidget_9.setGeometry(QtCore.QRect(500, 70, 471, 161))
        self.verticalLayoutWidget_9.setObjectName("verticalLayoutWidget_9")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_9)
        self.verticalLayout_9.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.horizontalLayout_33 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_33.setObjectName("horizontalLayout_33")
        self.setHAll_pushButton = QtWidgets.QPushButton(self.verticalLayoutWidget_9)
        self.setHAll_pushButton.setObjectName("setHAll_pushButton")
        self.horizontalLayout_33.addWidget(self.setHAll_pushButton)
        self.getHAll_pushButton = QtWidgets.QPushButton(self.verticalLayoutWidget_9)
        self.getHAll_pushButton.setObjectName("getHAll_pushButton")
        self.horizontalLayout_33.addWidget(self.getHAll_pushButton)
        self.disTHAll_pushButton = QtWidgets.QPushButton(self.verticalLayoutWidget_9)
        self.disTHAll_pushButton.setObjectName("disTHAll_pushButton")
        self.horizontalLayout_33.addWidget(self.disTHAll_pushButton)
        self.verticalLayout_9.addLayout(self.horizontalLayout_33)
        self.horizontalLayout_34 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_34.setObjectName("horizontalLayout_34")
        self.ID41_label = QtWidgets.QLabel(self.verticalLayoutWidget_9)
        self.ID41_label.setObjectName("ID41_label")
        self.horizontalLayout_34.addWidget(self.ID41_label)
        self.motorType41_label = QtWidgets.QLabel(self.verticalLayoutWidget_9)
        self.motorType41_label.setObjectName("motorType41_label")
        self.horizontalLayout_34.addWidget(self.motorType41_label)
        self.motor41center_label = QtWidgets.QLabel(self.verticalLayoutWidget_9)
        self.motor41center_label.setObjectName("motor41center_label")
        self.horizontalLayout_34.addWidget(self.motor41center_label)
        self.motor41Value_spinBox = QtWidgets.QSpinBox(self.verticalLayoutWidget_9)
        self.motor41Value_spinBox.setMaximum(4095)
        self.motor41Value_spinBox.setObjectName("motor41Value_spinBox")
        self.horizontalLayout_34.addWidget(self.motor41Value_spinBox)
        self.motor41value_dial = QtWidgets.QDial(self.verticalLayoutWidget_9)
        self.motor41value_dial.setMaximum(4095)
        self.motor41value_dial.setObjectName("motor41value_dial")
        self.horizontalLayout_34.addWidget(self.motor41value_dial)
        self.motor41Set_pushButton = QtWidgets.QPushButton(self.verticalLayoutWidget_9)
        self.motor41Set_pushButton.setObjectName("motor41Set_pushButton")
        self.horizontalLayout_34.addWidget(self.motor41Set_pushButton)
        self.motor41Get_pushButton = QtWidgets.QPushButton(self.verticalLayoutWidget_9)
        self.motor41Get_pushButton.setObjectName("motor41Get_pushButton")
        self.horizontalLayout_34.addWidget(self.motor41Get_pushButton)
        self.motor41DisT_pushButton = QtWidgets.QPushButton(self.verticalLayoutWidget_9)
        self.motor41DisT_pushButton.setObjectName("motor41DisT_pushButton")
        self.horizontalLayout_34.addWidget(self.motor41DisT_pushButton)
        self.verticalLayout_9.addLayout(self.horizontalLayout_34)
        self.horizontalLayout_35 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_35.setObjectName("horizontalLayout_35")
        self.ID42_label = QtWidgets.QLabel(self.verticalLayoutWidget_9)
        self.ID42_label.setObjectName("ID42_label")
        self.horizontalLayout_35.addWidget(self.ID42_label)
        self.motorType42_label = QtWidgets.QLabel(self.verticalLayoutWidget_9)
        self.motorType42_label.setObjectName("motorType42_label")
        self.horizontalLayout_35.addWidget(self.motorType42_label)
        self.motor42center_label = QtWidgets.QLabel(self.verticalLayoutWidget_9)
        self.motor42center_label.setObjectName("motor42center_label")
        self.horizontalLayout_35.addWidget(self.motor42center_label)
        self.motor42Value_spinBox = QtWidgets.QSpinBox(self.verticalLayoutWidget_9)
        self.motor42Value_spinBox.setMaximum(4095)
        self.motor42Value_spinBox.setObjectName("motor42Value_spinBox")
        self.horizontalLayout_35.addWidget(self.motor42Value_spinBox)
        self.motor42value_dial = QtWidgets.QDial(self.verticalLayoutWidget_9)
        self.motor42value_dial.setMaximum(4095)
        self.motor42value_dial.setObjectName("motor42value_dial")
        self.horizontalLayout_35.addWidget(self.motor42value_dial)
        self.motor42Set_pushButton = QtWidgets.QPushButton(self.verticalLayoutWidget_9)
        self.motor42Set_pushButton.setObjectName("motor42Set_pushButton")
        self.horizontalLayout_35.addWidget(self.motor42Set_pushButton)
        self.motor42Get_pushButton = QtWidgets.QPushButton(self.verticalLayoutWidget_9)
        self.motor42Get_pushButton.setObjectName("motor42Get_pushButton")
        self.horizontalLayout_35.addWidget(self.motor42Get_pushButton)
        self.motor42DisT_pushButton = QtWidgets.QPushButton(self.verticalLayoutWidget_9)
        self.motor42DisT_pushButton.setObjectName("motor42DisT_pushButton")
        self.horizontalLayout_35.addWidget(self.motor42DisT_pushButton)
        self.verticalLayout_9.addLayout(self.horizontalLayout_35)
        self.horizontalLayout_36 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_36.setObjectName("horizontalLayout_36")
        self.ID43_label = QtWidgets.QLabel(self.verticalLayoutWidget_9)
        self.ID43_label.setObjectName("ID43_label")
        self.horizontalLayout_36.addWidget(self.ID43_label)
        self.motorType43_label = QtWidgets.QLabel(self.verticalLayoutWidget_9)
        self.motorType43_label.setObjectName("motorType43_label")
        self.horizontalLayout_36.addWidget(self.motorType43_label)
        self.motor43center_label = QtWidgets.QLabel(self.verticalLayoutWidget_9)
        self.motor43center_label.setObjectName("motor43center_label")
        self.horizontalLayout_36.addWidget(self.motor43center_label)
        self.motor43Value_spinBox = QtWidgets.QSpinBox(self.verticalLayoutWidget_9)
        self.motor43Value_spinBox.setMaximum(4095)
        self.motor43Value_spinBox.setObjectName("motor43Value_spinBox")
        self.horizontalLayout_36.addWidget(self.motor43Value_spinBox)
        self.motor43value_dial = QtWidgets.QDial(self.verticalLayoutWidget_9)
        self.motor43value_dial.setMaximum(4095)
        self.motor43value_dial.setObjectName("motor43value_dial")
        self.horizontalLayout_36.addWidget(self.motor43value_dial)
        self.motor43Set_pushButton = QtWidgets.QPushButton(self.verticalLayoutWidget_9)
        self.motor43Set_pushButton.setObjectName("motor43Set_pushButton")
        self.horizontalLayout_36.addWidget(self.motor43Set_pushButton)
        self.motor43Get_pushButton = QtWidgets.QPushButton(self.verticalLayoutWidget_9)
        self.motor43Get_pushButton.setObjectName("motor43Get_pushButton")
        self.horizontalLayout_36.addWidget(self.motor43Get_pushButton)
        self.motor43DisT_pushButton = QtWidgets.QPushButton(self.verticalLayoutWidget_9)
        self.motor43DisT_pushButton.setObjectName("motor43DisT_pushButton")
        self.horizontalLayout_36.addWidget(self.motor43DisT_pushButton)
        self.verticalLayout_9.addLayout(self.horizontalLayout_36)
        self.loadFile_pushButton = QtWidgets.QPushButton(Form)
        self.loadFile_pushButton.setGeometry(QtCore.QRect(10, 30, 80, 22))
        self.loadFile_pushButton.setObjectName("loadFile_pushButton")
        self.saveFile_pushButton = QtWidgets.QPushButton(Form)
        self.saveFile_pushButton.setGeometry(QtCore.QRect(100, 30, 80, 22))
        self.saveFile_pushButton.setObjectName("saveFile_pushButton")
        self.horizontalLayoutWidget_4 = QtWidgets.QWidget(Form)
        self.horizontalLayoutWidget_4.setGeometry(QtCore.QRect(10, 60, 471, 21))
        self.horizontalLayoutWidget_4.setObjectName("horizontalLayoutWidget_4")
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_4)
        self.horizontalLayout_10.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.posture_label = QtWidgets.QLabel(self.horizontalLayoutWidget_4)
        self.posture_label.setObjectName("posture_label")
        self.horizontalLayout_10.addWidget(self.posture_label)
        self.postureName_label = QtWidgets.QLabel(self.horizontalLayoutWidget_4)
        self.postureName_label.setObjectName("postureName_label")
        self.horizontalLayout_10.addWidget(self.postureName_label)
        self.numOfKeyframe_label = QtWidgets.QLabel(self.horizontalLayoutWidget_4)
        self.numOfKeyframe_label.setObjectName("numOfKeyframe_label")
        self.horizontalLayout_10.addWidget(self.numOfKeyframe_label)
        self.numOfKeyframeStatus_label = QtWidgets.QLabel(self.horizontalLayoutWidget_4)
        self.numOfKeyframeStatus_label.setObjectName("numOfKeyframeStatus_label")
        self.horizontalLayout_10.addWidget(self.numOfKeyframeStatus_label)
        self.generateGetupFile_pushButton = QtWidgets.QPushButton(Form)
        self.generateGetupFile_pushButton.setGeometry(QtCore.QRect(310, 30, 171, 22))
        self.generateGetupFile_pushButton.setObjectName("generateGetupFile_pushButton")
        self.fileName_label = QtWidgets.QLabel(Form)
        self.fileName_label.setGeometry(QtCore.QRect(120, 10, 109, 19))
        self.fileName_label.setObjectName("fileName_label")
        self.file_label = QtWidgets.QLabel(Form)
        self.file_label.setGeometry(QtCore.QRect(10, 10, 152, 19))
        self.file_label.setObjectName("file_label")
        self.changeMotor_pushButton = QtWidgets.QPushButton(Form)
        self.changeMotor_pushButton.setGeometry(QtCore.QRect(190, 30, 111, 22))
        self.changeMotor_pushButton.setObjectName("changeMotor_pushButton")
        self.layoutWidget.raise_()
        self.layoutWidget.raise_()
        self.layoutWidget.raise_()
        self.layoutWidget.raise_()
        self.layoutWidget.raise_()
        self.horizontalLayoutWidget_3.raise_()
        self.horizontalLayoutWidget_2.raise_()
        self.horizontalLayoutWidget.raise_()
        self.verticalLayoutWidget_8.raise_()
        self.verticalLayoutWidget_9.raise_()
        self.verticalLayoutWidget_7.raise_()
        self.loadFile_pushButton.raise_()
        self.saveFile_pushButton.raise_()
        self.horizontalLayoutWidget_4.raise_()
        self.generateGetupFile_pushButton.raise_()
        self.fileName_label.raise_()
        self.file_label.raise_()
        self.changeMotor_pushButton.raise_()

        self.retranslateUi(Form)
        self.motor1value_dial.valueChanged['int'].connect(self.motor1Value_spinBox.setValue)
        self.motor1Value_spinBox.valueChanged['int'].connect(self.motor1value_dial.setValue)
        self.motor2value_dial.valueChanged['int'].connect(self.motor2Value_spinBox.setValue)
        self.motor2Value_spinBox.valueChanged['int'].connect(self.motor2value_dial.setValue)
        self.motor3value_dial.valueChanged['int'].connect(self.motor3Value_spinBox.setValue)
        self.motor3Value_spinBox.valueChanged['int'].connect(self.motor3value_dial.setValue)
        self.motor4value_dial.valueChanged['int'].connect(self.motor4Value_spinBox.setValue)
        self.motor4Value_spinBox.valueChanged['int'].connect(self.motor4value_dial.setValue)
        self.motor5value_dial.valueChanged['int'].connect(self.motor5Value_spinBox.setValue)
        self.motor5Value_spinBox.valueChanged['int'].connect(self.motor5value_dial.setValue)
        self.motor6value_dial.valueChanged['int'].connect(self.motor6Value_spinBox.setValue)
        self.motor6Value_spinBox.valueChanged['int'].connect(self.motor6value_dial.setValue)
        self.motor11value_dial.valueChanged['int'].connect(self.motor11Value_spinBox.setValue)
        self.motor11Value_spinBox.valueChanged['int'].connect(self.motor11value_dial.setValue)
        self.motor12value_dial.valueChanged['int'].connect(self.motor12Value_spinBox.setValue)
        self.motor12Value_spinBox.valueChanged['int'].connect(self.motor12value_dial.setValue)
        self.motor13value_dial.valueChanged['int'].connect(self.motor13Value_spinBox.setValue)
        self.motor13Value_spinBox.valueChanged['int'].connect(self.motor13value_dial.setValue)
        self.motor14value_dial.valueChanged['int'].connect(self.motor14Value_spinBox.setValue)
        self.motor14Value_spinBox.valueChanged['int'].connect(self.motor14value_dial.setValue)
        self.motor15value_dial.valueChanged['int'].connect(self.motor15Value_spinBox.setValue)
        self.motor15Value_spinBox.valueChanged['int'].connect(self.motor15value_dial.setValue)
        self.motor16value_dial.valueChanged['int'].connect(self.motor16Value_spinBox.setValue)
        self.motor16Value_spinBox.valueChanged['int'].connect(self.motor16value_dial.setValue)
        self.motor23value_dial.valueChanged['int'].connect(self.motor23Value_spinBox.setValue)
        self.motor23Value_spinBox.valueChanged['int'].connect(self.motor23value_dial.setValue)
        self.motor21value_dial.valueChanged['int'].connect(self.motor21Value_spinBox.setValue)
        self.motor21Value_spinBox.valueChanged['int'].connect(self.motor21value_dial.setValue)
        self.motor22value_dial.valueChanged['int'].connect(self.motor22Value_spinBox.setValue)
        self.motor22Value_spinBox.valueChanged['int'].connect(self.motor22value_dial.setValue)
        self.motor24value_dial.valueChanged['int'].connect(self.motor24Value_spinBox.setValue)
        self.motor24Value_spinBox.valueChanged['int'].connect(self.motor24value_dial.setValue)
        self.motor41Value_spinBox.valueChanged['int'].connect(self.motor41value_dial.setValue)
        self.motor41value_dial.valueChanged['int'].connect(self.motor41Value_spinBox.setValue)
        self.motor42Value_spinBox.valueChanged['int'].connect(self.motor42value_dial.setValue)
        self.motor42value_dial.valueChanged['int'].connect(self.motor42Value_spinBox.setValue)
        self.motor43Value_spinBox.valueChanged['int'].connect(self.motor43value_dial.setValue)
        self.motor43value_dial.valueChanged['int'].connect(self.motor43Value_spinBox.setValue)
        self.motor31Value_spinBox.valueChanged['int'].connect(self.motor31value_dial.setValue)
        self.motor31value_dial.valueChanged['int'].connect(self.motor31Value_spinBox.setValue)
        self.motor32Value_spinBox.valueChanged['int'].connect(self.motor32value_dial.setValue)
        self.motor32value_dial.valueChanged['int'].connect(self.motor32Value_spinBox.setValue)
        self.motor33Value_spinBox.valueChanged['int'].connect(self.motor33value_dial.setValue)
        self.motor33value_dial.valueChanged['int'].connect(self.motor33Value_spinBox.setValue)
        self.motor34Value_spinBox.valueChanged['int'].connect(self.motor34value_dial.setValue)
        self.motor34value_dial.valueChanged['int'].connect(self.motor34Value_spinBox.setValue)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.setLArmAll_pushButton.setText(_translate("Form", "Set L Arm All"))
        self.getLArmAll_pushButton.setText(_translate("Form", "Get L Arm All"))
        self.disTLArmAll_pushButton.setText(_translate("Form", "DisT L Arm All"))
        self.ID21_label.setText(_translate("Form", "ID21"))
        self.motorType21_label.setText(_translate("Form", "MX"))
        self.motor21center_label.setText(_translate("Form", "2048"))
        self.motor21Set_pushButton.setText(_translate("Form", "Set"))
        self.motor21Get_pushButton.setText(_translate("Form", "Get"))
        self.motor21DisT_pushButton.setText(_translate("Form", "DisT"))
        self.ID22_label.setText(_translate("Form", "ID22"))
        self.motorType22_label.setText(_translate("Form", "MX"))
        self.motor22center_label.setText(_translate("Form", "2048"))
        self.motor22Set_pushButton.setText(_translate("Form", "Set"))
        self.motor22Get_pushButton.setText(_translate("Form", "Get"))
        self.motor22DisT_pushButton.setText(_translate("Form", "DisT"))
        self.ID23_label.setText(_translate("Form", "ID23"))
        self.motorType23_label.setText(_translate("Form", "MX"))
        self.motor23center_label.setText(_translate("Form", "2048"))
        self.motor23Set_pushButton.setText(_translate("Form", "Set"))
        self.motor23Get_pushButton.setText(_translate("Form", "Get"))
        self.motor23DisT_pushButton.setText(_translate("Form", "DisT"))
        self.ID24_label.setText(_translate("Form", "ID24"))
        self.motorType24_label.setText(_translate("Form", "MX"))
        self.motor24center_label.setText(_translate("Form", "2048"))
        self.motor24Set_pushButton.setText(_translate("Form", "Set"))
        self.motor24Get_pushButton.setText(_translate("Form", "Get"))
        self.motor24DisT_pushButton.setText(_translate("Form", "DisT"))
        self.setRAll_pushButton.setText(_translate("Form", "Set R All"))
        self.getRAll_pushButton.setText(_translate("Form", "Get R All"))
        self.disTRAll_pushButton.setText(_translate("Form", "DisT R All"))
        self.ID11_label.setText(_translate("Form", "ID11"))
        self.motorType11_label.setText(_translate("Form", "MX"))
        self.motor11center_label.setText(_translate("Form", "2048"))
        self.motor11Set_pushButton.setText(_translate("Form", "Set"))
        self.motor11Get_pushButton.setText(_translate("Form", "Get"))
        self.motor11DisT_pushButton.setText(_translate("Form", "DisT"))
        self.ID12_label.setText(_translate("Form", "ID12"))
        self.motorType12_label.setText(_translate("Form", "MX"))
        self.motor12center_label.setText(_translate("Form", "2048"))
        self.motor12Set_pushButton.setText(_translate("Form", "Set"))
        self.motor12Get_pushButton.setText(_translate("Form", "Get"))
        self.motor12DisT_pushButton.setText(_translate("Form", "DisT"))
        self.ID13_label.setText(_translate("Form", "ID13"))
        self.motorType13_label.setText(_translate("Form", "MX"))
        self.motor13center_label.setText(_translate("Form", "2048"))
        self.motor13Set_pushButton.setText(_translate("Form", "Set"))
        self.motor13Get_pushButton.setText(_translate("Form", "Get"))
        self.motor13DisT_pushButton.setText(_translate("Form", "DisT"))
        self.ID14_label.setText(_translate("Form", "ID14"))
        self.motorType14_label.setText(_translate("Form", "MX"))
        self.motor14center_label.setText(_translate("Form", "2048"))
        self.motor14Set_pushButton.setText(_translate("Form", "Set"))
        self.motor14Get_pushButton.setText(_translate("Form", "Get"))
        self.motor14DisT_pushButton.setText(_translate("Form", "DisT"))
        self.ID15_label.setText(_translate("Form", "ID15"))
        self.motorType15_label.setText(_translate("Form", "MX"))
        self.motor15center_label.setText(_translate("Form", "2048"))
        self.motor15Set_pushButton.setText(_translate("Form", "Set"))
        self.motor15Get_pushButton.setText(_translate("Form", "Get"))
        self.motor15DisT_pushButton.setText(_translate("Form", "DisT"))
        self.ID7_label_.setText(_translate("Form", "ID16"))
        self.motorType16_label.setText(_translate("Form", "MX"))
        self.motor16center_label.setText(_translate("Form", "2048"))
        self.motor16Set_pushButton.setText(_translate("Form", "Set"))
        self.motor16Get_pushButton.setText(_translate("Form", "Get"))
        self.motor16DisT_pushButton.setText(_translate("Form", "DisT"))
        self.setLAll_pushButton.setText(_translate("Form", "Set L All"))
        self.getLAll_pushButton.setText(_translate("Form", "Get L All"))
        self.disTLAll_pushButton.setText(_translate("Form", "DisT L All"))
        self.ID1_label.setText(_translate("Form", "ID1"))
        self.motorType1_label.setText(_translate("Form", "MX"))
        self.motor1center_label.setText(_translate("Form", "2048"))
        self.motor1Set_pushButton.setText(_translate("Form", "Set"))
        self.motor1Get_pushButton.setText(_translate("Form", "Get"))
        self.motor1DisT_pushButton.setText(_translate("Form", "DisT"))
        self.ID2_label.setText(_translate("Form", "ID2"))
        self.motorType2_label.setText(_translate("Form", "MX"))
        self.motor2center_label.setText(_translate("Form", "2048"))
        self.motor2Set_pushButton.setText(_translate("Form", "Set"))
        self.motor2Get_pushButton.setText(_translate("Form", "Get"))
        self.motor2DisT_pushButton.setText(_translate("Form", "DisT"))
        self.ID3_label.setText(_translate("Form", "ID3"))
        self.motorType3_label.setText(_translate("Form", "MX"))
        self.motor3center_label.setText(_translate("Form", "2048"))
        self.motor3Set_pushButton.setText(_translate("Form", "Set"))
        self.motor3Get_pushButton.setText(_translate("Form", "Get"))
        self.motor3DisT_pushButton.setText(_translate("Form", "DisT"))
        self.ID4_label.setText(_translate("Form", "ID4"))
        self.motorType4_label.setText(_translate("Form", "MX"))
        self.motor4center_label.setText(_translate("Form", "2048"))
        self.motor4Set_pushButton.setText(_translate("Form", "Set"))
        self.motor4Get_pushButton.setText(_translate("Form", "Get"))
        self.motor4DisT_pushButton.setText(_translate("Form", "DisT"))
        self.ID5_label.setText(_translate("Form", "ID5"))
        self.motorType5_label.setText(_translate("Form", "MX"))
        self.motor5center_label.setText(_translate("Form", "2048"))
        self.motor5Set_pushButton.setText(_translate("Form", "Set"))
        self.motor5Get_pushButton.setText(_translate("Form", "Get"))
        self.motor5DisT_pushButton.setText(_translate("Form", "DisT"))
        self.ID6_label.setText(_translate("Form", "ID6"))
        self.motorType6_label.setText(_translate("Form", "MX"))
        self.motor6center_label.setText(_translate("Form", "2048"))
        self.motor6Set_pushButton.setText(_translate("Form", "Set"))
        self.motor6Get_pushButton.setText(_translate("Form", "Get"))
        self.motor6DisT_pushButton.setText(_translate("Form", "DisT"))
        self.play_label.setText(_translate("Form", "Play"))
        self.allKeyframe_label.setText(_translate("Form", "All Keyframe"))
        self.setReady_Button.setText(_translate("Form", "Set Ready"))
        self.playAll_Button.setText(_translate("Form", "Play All"))
        self.SelectedKeyframe_label.setText(_translate("Form", "Selected Keyframe"))
        self.activeKeyframe_checkBox.setText(_translate("Form", "Active Keyframe"))
        self.play_pushButton.setText(_translate("Form", "Play"))
        self.keyframeTime_label.setText(_translate("Form", "KF Time ="))
        self.setTime_pushButton.setText(_translate("Form", "Set Time"))
        self.setAll_pushButton.setText(_translate("Form", "Set All"))
        self.getAll_pushButton.setText(_translate("Form", "Get All"))
        self.disTAll_pushButton.setText(_translate("Form", "DisT All"))
        self.connectionStatus_label.setText(_translate("Form", "connection Status"))
        self.connect_Button.setText(_translate("Form", "Connect"))
        self.postureSelect_label.setText(_translate("Form", "Posture Select"))
        self.loadPosture_pushButton.setText(_translate("Form", "Load"))
        self.savePosture_pushButton.setText(_translate("Form", "Save"))
        self.saveCenter_pushButton.setText(_translate("Form", "Save Center"))
        self.deleteKeyframe_pushButton.setText(_translate("Form", "Delete"))
        self.duplicateKeyframe_pushButton.setText(_translate("Form", "Duplicate"))
        self.previousSwitchKeyframe_pushButton.setText(_translate("Form", "Previous Switch"))
        self.nextSwitchKeyframe_pushButton.setText(_translate("Form", "Next Switch"))
        self.setRArmAll_pushButton.setText(_translate("Form", "Set R Arm All"))
        self.getRArmAll_pushButton.setText(_translate("Form", "Get R Arm All"))
        self.disTRArmAll_pushButton.setText(_translate("Form", "DisT R Arm All"))
        self.ID31_label.setText(_translate("Form", "ID31"))
        self.motorType31_label.setText(_translate("Form", "MX"))
        self.motor31center_label.setText(_translate("Form", "2048"))
        self.motor31Set_pushButton.setText(_translate("Form", "Set"))
        self.motor31Get_pushButton.setText(_translate("Form", "Get"))
        self.motor31DisT_pushButton.setText(_translate("Form", "DisT"))
        self.ID32_label.setText(_translate("Form", "ID32"))
        self.motorType32_label.setText(_translate("Form", "MX"))
        self.motor32center_label.setText(_translate("Form", "2048"))
        self.motor32Set_pushButton.setText(_translate("Form", "Set"))
        self.motor32Get_pushButton.setText(_translate("Form", "Get"))
        self.motor32DisT_pushButton.setText(_translate("Form", "DisT"))
        self.ID33_label.setText(_translate("Form", "ID33"))
        self.motorType33_label.setText(_translate("Form", "MX"))
        self.motor33center_label.setText(_translate("Form", "2048"))
        self.motor33Set_pushButton.setText(_translate("Form", "Set"))
        self.motor33Get_pushButton.setText(_translate("Form", "Get"))
        self.motor33DisT_pushButton.setText(_translate("Form", "DisT"))
        self.ID34_label.setText(_translate("Form", "ID34"))
        self.motorType34_label.setText(_translate("Form", "MX"))
        self.motor34center_label.setText(_translate("Form", "2048"))
        self.motor34Set_pushButton.setText(_translate("Form", "Set"))
        self.motor34Get_pushButton.setText(_translate("Form", "Get"))
        self.motor34DisT_pushButton.setText(_translate("Form", "DisT"))
        self.setHAll_pushButton.setText(_translate("Form", "Set H All"))
        self.getHAll_pushButton.setText(_translate("Form", "Get H All"))
        self.disTHAll_pushButton.setText(_translate("Form", "DisT H All"))
        self.ID41_label.setText(_translate("Form", "ID41"))
        self.motorType41_label.setText(_translate("Form", "MX"))
        self.motor41center_label.setText(_translate("Form", "2048"))
        self.motor41Set_pushButton.setText(_translate("Form", "Set"))
        self.motor41Get_pushButton.setText(_translate("Form", "Get"))
        self.motor41DisT_pushButton.setText(_translate("Form", "DisT"))
        self.ID42_label.setText(_translate("Form", "ID42"))
        self.motorType42_label.setText(_translate("Form", "MX"))
        self.motor42center_label.setText(_translate("Form", "2048"))
        self.motor42Set_pushButton.setText(_translate("Form", "Set"))
        self.motor42Get_pushButton.setText(_translate("Form", "Get"))
        self.motor42DisT_pushButton.setText(_translate("Form", "DisT"))
        self.ID43_label.setText(_translate("Form", "ID43"))
        self.motorType43_label.setText(_translate("Form", "MX"))
        self.motor43center_label.setText(_translate("Form", "2048"))
        self.motor43Set_pushButton.setText(_translate("Form", "Set"))
        self.motor43Get_pushButton.setText(_translate("Form", "Get"))
        self.motor43DisT_pushButton.setText(_translate("Form", "DisT"))
        self.loadFile_pushButton.setText(_translate("Form", "load file"))
        self.saveFile_pushButton.setText(_translate("Form", "save file"))
        self.posture_label.setText(_translate("Form", "Posture::"))
        self.postureName_label.setText(_translate("Form", "Posture Name"))
        self.numOfKeyframe_label.setText(_translate("Form", "Number of Keyframe"))
        self.numOfKeyframeStatus_label.setText(_translate("Form", "0"))
        self.generateGetupFile_pushButton.setText(_translate("Form", "Generate Getup File"))
        self.fileName_label.setText(_translate("Form", "File Name"))
        self.file_label.setText(_translate("Form", "File::"))
        self.changeMotor_pushButton.setText(_translate("Form", "change motor"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())

