# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'SetPostureHumanoidUI.ui'
#
# Created: Mon May 04 16:39:42 2015
#      by: PyQt4 UI code generator 4.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName(_fromUtf8("Form"))
        Form.resize(906, 697)
        self.verticalLayoutWidget_7 = QtGui.QWidget(Form)
        self.verticalLayoutWidget_7.setGeometry(QtCore.QRect(10, 490, 441, 201))
        self.verticalLayoutWidget_7.setObjectName(_fromUtf8("verticalLayoutWidget_7"))
        self.verticalLayout_7 = QtGui.QVBoxLayout(self.verticalLayoutWidget_7)
        self.verticalLayout_7.setMargin(0)
        self.verticalLayout_7.setObjectName(_fromUtf8("verticalLayout_7"))
        self.horizontalLayout_26 = QtGui.QHBoxLayout()
        self.horizontalLayout_26.setObjectName(_fromUtf8("horizontalLayout_26"))
        self.setLArmAll_pushButton = QtGui.QPushButton(self.verticalLayoutWidget_7)
        self.setLArmAll_pushButton.setObjectName(_fromUtf8("setLArmAll_pushButton"))
        self.horizontalLayout_26.addWidget(self.setLArmAll_pushButton)
        self.getLArmAll_pushButton = QtGui.QPushButton(self.verticalLayoutWidget_7)
        self.getLArmAll_pushButton.setObjectName(_fromUtf8("getLArmAll_pushButton"))
        self.horizontalLayout_26.addWidget(self.getLArmAll_pushButton)
        self.disTLArmAll_pushButton = QtGui.QPushButton(self.verticalLayoutWidget_7)
        self.disTLArmAll_pushButton.setObjectName(_fromUtf8("disTLArmAll_pushButton"))
        self.horizontalLayout_26.addWidget(self.disTLArmAll_pushButton)
        self.verticalLayout_7.addLayout(self.horizontalLayout_26)
        self.horizontalLayout_20 = QtGui.QHBoxLayout()
        self.horizontalLayout_20.setObjectName(_fromUtf8("horizontalLayout_20"))
        self.ID21_label = QtGui.QLabel(self.verticalLayoutWidget_7)
        self.ID21_label.setObjectName(_fromUtf8("ID21_label"))
        self.horizontalLayout_20.addWidget(self.ID21_label)
        self.motorType21_label = QtGui.QLabel(self.verticalLayoutWidget_7)
        self.motorType21_label.setObjectName(_fromUtf8("motorType21_label"))
        self.horizontalLayout_20.addWidget(self.motorType21_label)
        self.motor21center_label = QtGui.QLabel(self.verticalLayoutWidget_7)
        self.motor21center_label.setObjectName(_fromUtf8("motor21center_label"))
        self.horizontalLayout_20.addWidget(self.motor21center_label)
        self.motor21Value_spinBox = QtGui.QSpinBox(self.verticalLayoutWidget_7)
        self.motor21Value_spinBox.setMaximum(4095)
        self.motor21Value_spinBox.setObjectName(_fromUtf8("motor21Value_spinBox"))
        self.horizontalLayout_20.addWidget(self.motor21Value_spinBox)
        self.motor21value_dial = QtGui.QDial(self.verticalLayoutWidget_7)
        self.motor21value_dial.setMaximum(4095)
        self.motor21value_dial.setObjectName(_fromUtf8("motor21value_dial"))
        self.horizontalLayout_20.addWidget(self.motor21value_dial)
        self.motor21Set_pushButton = QtGui.QPushButton(self.verticalLayoutWidget_7)
        self.motor21Set_pushButton.setObjectName(_fromUtf8("motor21Set_pushButton"))
        self.horizontalLayout_20.addWidget(self.motor21Set_pushButton)
        self.motor21Get_pushButton = QtGui.QPushButton(self.verticalLayoutWidget_7)
        self.motor21Get_pushButton.setObjectName(_fromUtf8("motor21Get_pushButton"))
        self.horizontalLayout_20.addWidget(self.motor21Get_pushButton)
        self.motor21DisT_pushButton = QtGui.QPushButton(self.verticalLayoutWidget_7)
        self.motor21DisT_pushButton.setObjectName(_fromUtf8("motor21DisT_pushButton"))
        self.horizontalLayout_20.addWidget(self.motor21DisT_pushButton)
        self.verticalLayout_7.addLayout(self.horizontalLayout_20)
        self.horizontalLayout_21 = QtGui.QHBoxLayout()
        self.horizontalLayout_21.setObjectName(_fromUtf8("horizontalLayout_21"))
        self.ID22_label = QtGui.QLabel(self.verticalLayoutWidget_7)
        self.ID22_label.setObjectName(_fromUtf8("ID22_label"))
        self.horizontalLayout_21.addWidget(self.ID22_label)
        self.motorType22_label = QtGui.QLabel(self.verticalLayoutWidget_7)
        self.motorType22_label.setObjectName(_fromUtf8("motorType22_label"))
        self.horizontalLayout_21.addWidget(self.motorType22_label)
        self.motor22center_label = QtGui.QLabel(self.verticalLayoutWidget_7)
        self.motor22center_label.setObjectName(_fromUtf8("motor22center_label"))
        self.horizontalLayout_21.addWidget(self.motor22center_label)
        self.motor22Value_spinBox = QtGui.QSpinBox(self.verticalLayoutWidget_7)
        self.motor22Value_spinBox.setMaximum(4095)
        self.motor22Value_spinBox.setObjectName(_fromUtf8("motor22Value_spinBox"))
        self.horizontalLayout_21.addWidget(self.motor22Value_spinBox)
        self.motor22value_dial = QtGui.QDial(self.verticalLayoutWidget_7)
        self.motor22value_dial.setMaximum(4095)
        self.motor22value_dial.setObjectName(_fromUtf8("motor22value_dial"))
        self.horizontalLayout_21.addWidget(self.motor22value_dial)
        self.motor22Set_pushButton = QtGui.QPushButton(self.verticalLayoutWidget_7)
        self.motor22Set_pushButton.setObjectName(_fromUtf8("motor22Set_pushButton"))
        self.horizontalLayout_21.addWidget(self.motor22Set_pushButton)
        self.motor22Get_pushButton = QtGui.QPushButton(self.verticalLayoutWidget_7)
        self.motor22Get_pushButton.setObjectName(_fromUtf8("motor22Get_pushButton"))
        self.horizontalLayout_21.addWidget(self.motor22Get_pushButton)
        self.motor22DisT_pushButton = QtGui.QPushButton(self.verticalLayoutWidget_7)
        self.motor22DisT_pushButton.setObjectName(_fromUtf8("motor22DisT_pushButton"))
        self.horizontalLayout_21.addWidget(self.motor22DisT_pushButton)
        self.verticalLayout_7.addLayout(self.horizontalLayout_21)
        self.horizontalLayout_19 = QtGui.QHBoxLayout()
        self.horizontalLayout_19.setObjectName(_fromUtf8("horizontalLayout_19"))
        self.ID23_label = QtGui.QLabel(self.verticalLayoutWidget_7)
        self.ID23_label.setObjectName(_fromUtf8("ID23_label"))
        self.horizontalLayout_19.addWidget(self.ID23_label)
        self.motorType23_label = QtGui.QLabel(self.verticalLayoutWidget_7)
        self.motorType23_label.setObjectName(_fromUtf8("motorType23_label"))
        self.horizontalLayout_19.addWidget(self.motorType23_label)
        self.motor23center_label = QtGui.QLabel(self.verticalLayoutWidget_7)
        self.motor23center_label.setObjectName(_fromUtf8("motor23center_label"))
        self.horizontalLayout_19.addWidget(self.motor23center_label)
        self.motor23Value_spinBox = QtGui.QSpinBox(self.verticalLayoutWidget_7)
        self.motor23Value_spinBox.setMaximum(4095)
        self.motor23Value_spinBox.setObjectName(_fromUtf8("motor23Value_spinBox"))
        self.horizontalLayout_19.addWidget(self.motor23Value_spinBox)
        self.motor23value_dial = QtGui.QDial(self.verticalLayoutWidget_7)
        self.motor23value_dial.setMaximum(4095)
        self.motor23value_dial.setObjectName(_fromUtf8("motor23value_dial"))
        self.horizontalLayout_19.addWidget(self.motor23value_dial)
        self.motor23Set_pushButton = QtGui.QPushButton(self.verticalLayoutWidget_7)
        self.motor23Set_pushButton.setObjectName(_fromUtf8("motor23Set_pushButton"))
        self.horizontalLayout_19.addWidget(self.motor23Set_pushButton)
        self.motor23Get_pushButton = QtGui.QPushButton(self.verticalLayoutWidget_7)
        self.motor23Get_pushButton.setObjectName(_fromUtf8("motor23Get_pushButton"))
        self.horizontalLayout_19.addWidget(self.motor23Get_pushButton)
        self.motor23DisT_pushButton = QtGui.QPushButton(self.verticalLayoutWidget_7)
        self.motor23DisT_pushButton.setObjectName(_fromUtf8("motor23DisT_pushButton"))
        self.horizontalLayout_19.addWidget(self.motor23DisT_pushButton)
        self.verticalLayout_7.addLayout(self.horizontalLayout_19)
        self.horizontalLayout_27 = QtGui.QHBoxLayout()
        self.horizontalLayout_27.setObjectName(_fromUtf8("horizontalLayout_27"))
        self.ID24_label = QtGui.QLabel(self.verticalLayoutWidget_7)
        self.ID24_label.setObjectName(_fromUtf8("ID24_label"))
        self.horizontalLayout_27.addWidget(self.ID24_label)
        self.motorType24_label = QtGui.QLabel(self.verticalLayoutWidget_7)
        self.motorType24_label.setObjectName(_fromUtf8("motorType24_label"))
        self.horizontalLayout_27.addWidget(self.motorType24_label)
        self.motor24center_label = QtGui.QLabel(self.verticalLayoutWidget_7)
        self.motor24center_label.setObjectName(_fromUtf8("motor24center_label"))
        self.horizontalLayout_27.addWidget(self.motor24center_label)
        self.motor24Value_spinBox = QtGui.QSpinBox(self.verticalLayoutWidget_7)
        self.motor24Value_spinBox.setMaximum(4095)
        self.motor24Value_spinBox.setObjectName(_fromUtf8("motor24Value_spinBox"))
        self.horizontalLayout_27.addWidget(self.motor24Value_spinBox)
        self.motor24value_dial = QtGui.QDial(self.verticalLayoutWidget_7)
        self.motor24value_dial.setMaximum(4095)
        self.motor24value_dial.setObjectName(_fromUtf8("motor24value_dial"))
        self.horizontalLayout_27.addWidget(self.motor24value_dial)
        self.motor24Set_pushButton = QtGui.QPushButton(self.verticalLayoutWidget_7)
        self.motor24Set_pushButton.setObjectName(_fromUtf8("motor24Set_pushButton"))
        self.horizontalLayout_27.addWidget(self.motor24Set_pushButton)
        self.motor24Get_pushButton = QtGui.QPushButton(self.verticalLayoutWidget_7)
        self.motor24Get_pushButton.setObjectName(_fromUtf8("motor24Get_pushButton"))
        self.horizontalLayout_27.addWidget(self.motor24Get_pushButton)
        self.motor24DisT_pushButton = QtGui.QPushButton(self.verticalLayoutWidget_7)
        self.motor24DisT_pushButton.setObjectName(_fromUtf8("motor24DisT_pushButton"))
        self.horizontalLayout_27.addWidget(self.motor24DisT_pushButton)
        self.verticalLayout_7.addLayout(self.horizontalLayout_27)
        self.layoutWidget = QtGui.QWidget(Form)
        self.layoutWidget.setGeometry(QtCore.QRect(460, 190, 441, 291))
        self.layoutWidget.setObjectName(_fromUtf8("layoutWidget"))
        self.verticalLayout_6 = QtGui.QVBoxLayout(self.layoutWidget)
        self.verticalLayout_6.setMargin(0)
        self.verticalLayout_6.setObjectName(_fromUtf8("verticalLayout_6"))
        self.horizontalLayout_25 = QtGui.QHBoxLayout()
        self.horizontalLayout_25.setObjectName(_fromUtf8("horizontalLayout_25"))
        self.setRAll_pushButton = QtGui.QPushButton(self.layoutWidget)
        self.setRAll_pushButton.setObjectName(_fromUtf8("setRAll_pushButton"))
        self.horizontalLayout_25.addWidget(self.setRAll_pushButton)
        self.getRAll_pushButton = QtGui.QPushButton(self.layoutWidget)
        self.getRAll_pushButton.setObjectName(_fromUtf8("getRAll_pushButton"))
        self.horizontalLayout_25.addWidget(self.getRAll_pushButton)
        self.disTRAll_pushButton = QtGui.QPushButton(self.layoutWidget)
        self.disTRAll_pushButton.setObjectName(_fromUtf8("disTRAll_pushButton"))
        self.horizontalLayout_25.addWidget(self.disTRAll_pushButton)
        self.verticalLayout_6.addLayout(self.horizontalLayout_25)
        self.horizontalLayout_12 = QtGui.QHBoxLayout()
        self.horizontalLayout_12.setObjectName(_fromUtf8("horizontalLayout_12"))
        self.ID11_label = QtGui.QLabel(self.layoutWidget)
        self.ID11_label.setObjectName(_fromUtf8("ID11_label"))
        self.horizontalLayout_12.addWidget(self.ID11_label)
        self.motorType11_label = QtGui.QLabel(self.layoutWidget)
        self.motorType11_label.setObjectName(_fromUtf8("motorType11_label"))
        self.horizontalLayout_12.addWidget(self.motorType11_label)
        self.motor11center_label = QtGui.QLabel(self.layoutWidget)
        self.motor11center_label.setObjectName(_fromUtf8("motor11center_label"))
        self.horizontalLayout_12.addWidget(self.motor11center_label)
        self.motor11Value_spinBox = QtGui.QSpinBox(self.layoutWidget)
        self.motor11Value_spinBox.setMaximum(4095)
        self.motor11Value_spinBox.setObjectName(_fromUtf8("motor11Value_spinBox"))
        self.horizontalLayout_12.addWidget(self.motor11Value_spinBox)
        self.motor11value_dial = QtGui.QDial(self.layoutWidget)
        self.motor11value_dial.setMaximum(4095)
        self.motor11value_dial.setObjectName(_fromUtf8("motor11value_dial"))
        self.horizontalLayout_12.addWidget(self.motor11value_dial)
        self.motor11Set_pushButton = QtGui.QPushButton(self.layoutWidget)
        self.motor11Set_pushButton.setObjectName(_fromUtf8("motor11Set_pushButton"))
        self.horizontalLayout_12.addWidget(self.motor11Set_pushButton)
        self.motor11Get_pushButton = QtGui.QPushButton(self.layoutWidget)
        self.motor11Get_pushButton.setObjectName(_fromUtf8("motor11Get_pushButton"))
        self.horizontalLayout_12.addWidget(self.motor11Get_pushButton)
        self.motor11DisT_pushButton = QtGui.QPushButton(self.layoutWidget)
        self.motor11DisT_pushButton.setObjectName(_fromUtf8("motor11DisT_pushButton"))
        self.horizontalLayout_12.addWidget(self.motor11DisT_pushButton)
        self.verticalLayout_6.addLayout(self.horizontalLayout_12)
        self.horizontalLayout_13 = QtGui.QHBoxLayout()
        self.horizontalLayout_13.setObjectName(_fromUtf8("horizontalLayout_13"))
        self.ID12_label = QtGui.QLabel(self.layoutWidget)
        self.ID12_label.setObjectName(_fromUtf8("ID12_label"))
        self.horizontalLayout_13.addWidget(self.ID12_label)
        self.motorType12_label = QtGui.QLabel(self.layoutWidget)
        self.motorType12_label.setObjectName(_fromUtf8("motorType12_label"))
        self.horizontalLayout_13.addWidget(self.motorType12_label)
        self.motor12center_label = QtGui.QLabel(self.layoutWidget)
        self.motor12center_label.setObjectName(_fromUtf8("motor12center_label"))
        self.horizontalLayout_13.addWidget(self.motor12center_label)
        self.motor12Value_spinBox = QtGui.QSpinBox(self.layoutWidget)
        self.motor12Value_spinBox.setMaximum(4095)
        self.motor12Value_spinBox.setObjectName(_fromUtf8("motor12Value_spinBox"))
        self.horizontalLayout_13.addWidget(self.motor12Value_spinBox)
        self.motor12value_dial = QtGui.QDial(self.layoutWidget)
        self.motor12value_dial.setMaximum(4095)
        self.motor12value_dial.setObjectName(_fromUtf8("motor12value_dial"))
        self.horizontalLayout_13.addWidget(self.motor12value_dial)
        self.motor12Set_pushButton = QtGui.QPushButton(self.layoutWidget)
        self.motor12Set_pushButton.setObjectName(_fromUtf8("motor12Set_pushButton"))
        self.horizontalLayout_13.addWidget(self.motor12Set_pushButton)
        self.motor12Get_pushButton = QtGui.QPushButton(self.layoutWidget)
        self.motor12Get_pushButton.setObjectName(_fromUtf8("motor12Get_pushButton"))
        self.horizontalLayout_13.addWidget(self.motor12Get_pushButton)
        self.motor12DisT_pushButton = QtGui.QPushButton(self.layoutWidget)
        self.motor12DisT_pushButton.setObjectName(_fromUtf8("motor12DisT_pushButton"))
        self.horizontalLayout_13.addWidget(self.motor12DisT_pushButton)
        self.verticalLayout_6.addLayout(self.horizontalLayout_13)
        self.horizontalLayout_14 = QtGui.QHBoxLayout()
        self.horizontalLayout_14.setObjectName(_fromUtf8("horizontalLayout_14"))
        self.ID13_label = QtGui.QLabel(self.layoutWidget)
        self.ID13_label.setObjectName(_fromUtf8("ID13_label"))
        self.horizontalLayout_14.addWidget(self.ID13_label)
        self.motorType13_label = QtGui.QLabel(self.layoutWidget)
        self.motorType13_label.setObjectName(_fromUtf8("motorType13_label"))
        self.horizontalLayout_14.addWidget(self.motorType13_label)
        self.motor13center_label = QtGui.QLabel(self.layoutWidget)
        self.motor13center_label.setObjectName(_fromUtf8("motor13center_label"))
        self.horizontalLayout_14.addWidget(self.motor13center_label)
        self.motor13Value_spinBox = QtGui.QSpinBox(self.layoutWidget)
        self.motor13Value_spinBox.setMaximum(4095)
        self.motor13Value_spinBox.setObjectName(_fromUtf8("motor13Value_spinBox"))
        self.horizontalLayout_14.addWidget(self.motor13Value_spinBox)
        self.motor13value_dial = QtGui.QDial(self.layoutWidget)
        self.motor13value_dial.setMaximum(4095)
        self.motor13value_dial.setObjectName(_fromUtf8("motor13value_dial"))
        self.horizontalLayout_14.addWidget(self.motor13value_dial)
        self.motor13Set_pushButton = QtGui.QPushButton(self.layoutWidget)
        self.motor13Set_pushButton.setObjectName(_fromUtf8("motor13Set_pushButton"))
        self.horizontalLayout_14.addWidget(self.motor13Set_pushButton)
        self.motor13Get_pushButton = QtGui.QPushButton(self.layoutWidget)
        self.motor13Get_pushButton.setObjectName(_fromUtf8("motor13Get_pushButton"))
        self.horizontalLayout_14.addWidget(self.motor13Get_pushButton)
        self.motor13DisT_pushButton = QtGui.QPushButton(self.layoutWidget)
        self.motor13DisT_pushButton.setObjectName(_fromUtf8("motor13DisT_pushButton"))
        self.horizontalLayout_14.addWidget(self.motor13DisT_pushButton)
        self.verticalLayout_6.addLayout(self.horizontalLayout_14)
        self.horizontalLayout_15 = QtGui.QHBoxLayout()
        self.horizontalLayout_15.setObjectName(_fromUtf8("horizontalLayout_15"))
        self.ID14_label = QtGui.QLabel(self.layoutWidget)
        self.ID14_label.setObjectName(_fromUtf8("ID14_label"))
        self.horizontalLayout_15.addWidget(self.ID14_label)
        self.motorType14_label = QtGui.QLabel(self.layoutWidget)
        self.motorType14_label.setObjectName(_fromUtf8("motorType14_label"))
        self.horizontalLayout_15.addWidget(self.motorType14_label)
        self.motor14center_label = QtGui.QLabel(self.layoutWidget)
        self.motor14center_label.setObjectName(_fromUtf8("motor14center_label"))
        self.horizontalLayout_15.addWidget(self.motor14center_label)
        self.motor14Value_spinBox = QtGui.QSpinBox(self.layoutWidget)
        self.motor14Value_spinBox.setMaximum(4095)
        self.motor14Value_spinBox.setObjectName(_fromUtf8("motor14Value_spinBox"))
        self.horizontalLayout_15.addWidget(self.motor14Value_spinBox)
        self.motor14value_dial = QtGui.QDial(self.layoutWidget)
        self.motor14value_dial.setMaximum(4095)
        self.motor14value_dial.setObjectName(_fromUtf8("motor14value_dial"))
        self.horizontalLayout_15.addWidget(self.motor14value_dial)
        self.motor14Set_pushButton = QtGui.QPushButton(self.layoutWidget)
        self.motor14Set_pushButton.setObjectName(_fromUtf8("motor14Set_pushButton"))
        self.horizontalLayout_15.addWidget(self.motor14Set_pushButton)
        self.motor14Get_pushButton = QtGui.QPushButton(self.layoutWidget)
        self.motor14Get_pushButton.setObjectName(_fromUtf8("motor14Get_pushButton"))
        self.horizontalLayout_15.addWidget(self.motor14Get_pushButton)
        self.motor14DisT_pushButton = QtGui.QPushButton(self.layoutWidget)
        self.motor14DisT_pushButton.setObjectName(_fromUtf8("motor14DisT_pushButton"))
        self.horizontalLayout_15.addWidget(self.motor14DisT_pushButton)
        self.verticalLayout_6.addLayout(self.horizontalLayout_15)
        self.horizontalLayout_16 = QtGui.QHBoxLayout()
        self.horizontalLayout_16.setObjectName(_fromUtf8("horizontalLayout_16"))
        self.ID15_label = QtGui.QLabel(self.layoutWidget)
        self.ID15_label.setObjectName(_fromUtf8("ID15_label"))
        self.horizontalLayout_16.addWidget(self.ID15_label)
        self.motorType15_label = QtGui.QLabel(self.layoutWidget)
        self.motorType15_label.setObjectName(_fromUtf8("motorType15_label"))
        self.horizontalLayout_16.addWidget(self.motorType15_label)
        self.motor15center_label = QtGui.QLabel(self.layoutWidget)
        self.motor15center_label.setObjectName(_fromUtf8("motor15center_label"))
        self.horizontalLayout_16.addWidget(self.motor15center_label)
        self.motor15Value_spinBox = QtGui.QSpinBox(self.layoutWidget)
        self.motor15Value_spinBox.setMaximum(4095)
        self.motor15Value_spinBox.setObjectName(_fromUtf8("motor15Value_spinBox"))
        self.horizontalLayout_16.addWidget(self.motor15Value_spinBox)
        self.motor15value_dial = QtGui.QDial(self.layoutWidget)
        self.motor15value_dial.setMaximum(4095)
        self.motor15value_dial.setObjectName(_fromUtf8("motor15value_dial"))
        self.horizontalLayout_16.addWidget(self.motor15value_dial)
        self.motor15Set_pushButton = QtGui.QPushButton(self.layoutWidget)
        self.motor15Set_pushButton.setObjectName(_fromUtf8("motor15Set_pushButton"))
        self.horizontalLayout_16.addWidget(self.motor15Set_pushButton)
        self.motor15Get_pushButton = QtGui.QPushButton(self.layoutWidget)
        self.motor15Get_pushButton.setObjectName(_fromUtf8("motor15Get_pushButton"))
        self.horizontalLayout_16.addWidget(self.motor15Get_pushButton)
        self.motor15DisT_pushButton = QtGui.QPushButton(self.layoutWidget)
        self.motor15DisT_pushButton.setObjectName(_fromUtf8("motor15DisT_pushButton"))
        self.horizontalLayout_16.addWidget(self.motor15DisT_pushButton)
        self.verticalLayout_6.addLayout(self.horizontalLayout_16)
        self.horizontalLayout_17 = QtGui.QHBoxLayout()
        self.horizontalLayout_17.setObjectName(_fromUtf8("horizontalLayout_17"))
        self.ID7_label_ = QtGui.QLabel(self.layoutWidget)
        self.ID7_label_.setObjectName(_fromUtf8("ID7_label_"))
        self.horizontalLayout_17.addWidget(self.ID7_label_)
        self.motorType16_label = QtGui.QLabel(self.layoutWidget)
        self.motorType16_label.setObjectName(_fromUtf8("motorType16_label"))
        self.horizontalLayout_17.addWidget(self.motorType16_label)
        self.motor16center_label = QtGui.QLabel(self.layoutWidget)
        self.motor16center_label.setObjectName(_fromUtf8("motor16center_label"))
        self.horizontalLayout_17.addWidget(self.motor16center_label)
        self.motor16Value_spinBox = QtGui.QSpinBox(self.layoutWidget)
        self.motor16Value_spinBox.setMaximum(4095)
        self.motor16Value_spinBox.setObjectName(_fromUtf8("motor16Value_spinBox"))
        self.horizontalLayout_17.addWidget(self.motor16Value_spinBox)
        self.motor16value_dial = QtGui.QDial(self.layoutWidget)
        self.motor16value_dial.setMaximum(4095)
        self.motor16value_dial.setObjectName(_fromUtf8("motor16value_dial"))
        self.horizontalLayout_17.addWidget(self.motor16value_dial)
        self.motor16Set_pushButton = QtGui.QPushButton(self.layoutWidget)
        self.motor16Set_pushButton.setObjectName(_fromUtf8("motor16Set_pushButton"))
        self.horizontalLayout_17.addWidget(self.motor16Set_pushButton)
        self.motor16Get_pushButton = QtGui.QPushButton(self.layoutWidget)
        self.motor16Get_pushButton.setObjectName(_fromUtf8("motor16Get_pushButton"))
        self.horizontalLayout_17.addWidget(self.motor16Get_pushButton)
        self.motor16DisT_pushButton = QtGui.QPushButton(self.layoutWidget)
        self.motor16DisT_pushButton.setObjectName(_fromUtf8("motor16DisT_pushButton"))
        self.horizontalLayout_17.addWidget(self.motor16DisT_pushButton)
        self.verticalLayout_6.addLayout(self.horizontalLayout_17)
        self.layoutWidget1 = QtGui.QWidget(Form)
        self.layoutWidget1.setGeometry(QtCore.QRect(10, 190, 441, 291))
        self.layoutWidget1.setObjectName(_fromUtf8("layoutWidget1"))
        self.verticalLayout_5 = QtGui.QVBoxLayout(self.layoutWidget1)
        self.verticalLayout_5.setMargin(0)
        self.verticalLayout_5.setObjectName(_fromUtf8("verticalLayout_5"))
        self.horizontalLayout_22 = QtGui.QHBoxLayout()
        self.horizontalLayout_22.setObjectName(_fromUtf8("horizontalLayout_22"))
        self.setLAll_pushButton = QtGui.QPushButton(self.layoutWidget1)
        self.setLAll_pushButton.setObjectName(_fromUtf8("setLAll_pushButton"))
        self.horizontalLayout_22.addWidget(self.setLAll_pushButton)
        self.getLAll_pushButton = QtGui.QPushButton(self.layoutWidget1)
        self.getLAll_pushButton.setObjectName(_fromUtf8("getLAll_pushButton"))
        self.horizontalLayout_22.addWidget(self.getLAll_pushButton)
        self.disTLAll_pushButton = QtGui.QPushButton(self.layoutWidget1)
        self.disTLAll_pushButton.setObjectName(_fromUtf8("disTLAll_pushButton"))
        self.horizontalLayout_22.addWidget(self.disTLAll_pushButton)
        self.verticalLayout_5.addLayout(self.horizontalLayout_22)
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.ID1_label = QtGui.QLabel(self.layoutWidget1)
        self.ID1_label.setObjectName(_fromUtf8("ID1_label"))
        self.horizontalLayout_4.addWidget(self.ID1_label)
        self.motorType1_label = QtGui.QLabel(self.layoutWidget1)
        self.motorType1_label.setObjectName(_fromUtf8("motorType1_label"))
        self.horizontalLayout_4.addWidget(self.motorType1_label)
        self.motor1center_label = QtGui.QLabel(self.layoutWidget1)
        self.motor1center_label.setObjectName(_fromUtf8("motor1center_label"))
        self.horizontalLayout_4.addWidget(self.motor1center_label)
        self.motor1Value_spinBox = QtGui.QSpinBox(self.layoutWidget1)
        self.motor1Value_spinBox.setMaximum(4095)
        self.motor1Value_spinBox.setObjectName(_fromUtf8("motor1Value_spinBox"))
        self.horizontalLayout_4.addWidget(self.motor1Value_spinBox)
        self.motor1value_dial = QtGui.QDial(self.layoutWidget1)
        self.motor1value_dial.setMaximum(4095)
        self.motor1value_dial.setObjectName(_fromUtf8("motor1value_dial"))
        self.horizontalLayout_4.addWidget(self.motor1value_dial)
        self.motor1Set_pushButton = QtGui.QPushButton(self.layoutWidget1)
        self.motor1Set_pushButton.setObjectName(_fromUtf8("motor1Set_pushButton"))
        self.horizontalLayout_4.addWidget(self.motor1Set_pushButton)
        self.motor1Get_pushButton = QtGui.QPushButton(self.layoutWidget1)
        self.motor1Get_pushButton.setObjectName(_fromUtf8("motor1Get_pushButton"))
        self.horizontalLayout_4.addWidget(self.motor1Get_pushButton)
        self.motor1DisT_pushButton = QtGui.QPushButton(self.layoutWidget1)
        self.motor1DisT_pushButton.setObjectName(_fromUtf8("motor1DisT_pushButton"))
        self.horizontalLayout_4.addWidget(self.motor1DisT_pushButton)
        self.verticalLayout_5.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        self.ID2_label = QtGui.QLabel(self.layoutWidget1)
        self.ID2_label.setObjectName(_fromUtf8("ID2_label"))
        self.horizontalLayout_5.addWidget(self.ID2_label)
        self.motorType2_label = QtGui.QLabel(self.layoutWidget1)
        self.motorType2_label.setObjectName(_fromUtf8("motorType2_label"))
        self.horizontalLayout_5.addWidget(self.motorType2_label)
        self.motor2center_label = QtGui.QLabel(self.layoutWidget1)
        self.motor2center_label.setObjectName(_fromUtf8("motor2center_label"))
        self.horizontalLayout_5.addWidget(self.motor2center_label)
        self.motor2Value_spinBox = QtGui.QSpinBox(self.layoutWidget1)
        self.motor2Value_spinBox.setMaximum(4095)
        self.motor2Value_spinBox.setObjectName(_fromUtf8("motor2Value_spinBox"))
        self.horizontalLayout_5.addWidget(self.motor2Value_spinBox)
        self.motor2value_dial = QtGui.QDial(self.layoutWidget1)
        self.motor2value_dial.setMaximum(4095)
        self.motor2value_dial.setObjectName(_fromUtf8("motor2value_dial"))
        self.horizontalLayout_5.addWidget(self.motor2value_dial)
        self.motor2Set_pushButton = QtGui.QPushButton(self.layoutWidget1)
        self.motor2Set_pushButton.setObjectName(_fromUtf8("motor2Set_pushButton"))
        self.horizontalLayout_5.addWidget(self.motor2Set_pushButton)
        self.motor2Get_pushButton = QtGui.QPushButton(self.layoutWidget1)
        self.motor2Get_pushButton.setObjectName(_fromUtf8("motor2Get_pushButton"))
        self.horizontalLayout_5.addWidget(self.motor2Get_pushButton)
        self.motor2DisT_pushButton = QtGui.QPushButton(self.layoutWidget1)
        self.motor2DisT_pushButton.setObjectName(_fromUtf8("motor2DisT_pushButton"))
        self.horizontalLayout_5.addWidget(self.motor2DisT_pushButton)
        self.verticalLayout_5.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_6 = QtGui.QHBoxLayout()
        self.horizontalLayout_6.setObjectName(_fromUtf8("horizontalLayout_6"))
        self.ID3_label = QtGui.QLabel(self.layoutWidget1)
        self.ID3_label.setObjectName(_fromUtf8("ID3_label"))
        self.horizontalLayout_6.addWidget(self.ID3_label)
        self.motorType3_label = QtGui.QLabel(self.layoutWidget1)
        self.motorType3_label.setObjectName(_fromUtf8("motorType3_label"))
        self.horizontalLayout_6.addWidget(self.motorType3_label)
        self.motor3center_label = QtGui.QLabel(self.layoutWidget1)
        self.motor3center_label.setObjectName(_fromUtf8("motor3center_label"))
        self.horizontalLayout_6.addWidget(self.motor3center_label)
        self.motor3Value_spinBox = QtGui.QSpinBox(self.layoutWidget1)
        self.motor3Value_spinBox.setMaximum(4095)
        self.motor3Value_spinBox.setObjectName(_fromUtf8("motor3Value_spinBox"))
        self.horizontalLayout_6.addWidget(self.motor3Value_spinBox)
        self.motor3value_dial = QtGui.QDial(self.layoutWidget1)
        self.motor3value_dial.setMaximum(4095)
        self.motor3value_dial.setObjectName(_fromUtf8("motor3value_dial"))
        self.horizontalLayout_6.addWidget(self.motor3value_dial)
        self.motor3Set_pushButton = QtGui.QPushButton(self.layoutWidget1)
        self.motor3Set_pushButton.setObjectName(_fromUtf8("motor3Set_pushButton"))
        self.horizontalLayout_6.addWidget(self.motor3Set_pushButton)
        self.motor3Get_pushButton = QtGui.QPushButton(self.layoutWidget1)
        self.motor3Get_pushButton.setObjectName(_fromUtf8("motor3Get_pushButton"))
        self.horizontalLayout_6.addWidget(self.motor3Get_pushButton)
        self.motor3DisT_pushButton = QtGui.QPushButton(self.layoutWidget1)
        self.motor3DisT_pushButton.setObjectName(_fromUtf8("motor3DisT_pushButton"))
        self.horizontalLayout_6.addWidget(self.motor3DisT_pushButton)
        self.verticalLayout_5.addLayout(self.horizontalLayout_6)
        self.horizontalLayout_7 = QtGui.QHBoxLayout()
        self.horizontalLayout_7.setObjectName(_fromUtf8("horizontalLayout_7"))
        self.ID4_label = QtGui.QLabel(self.layoutWidget1)
        self.ID4_label.setObjectName(_fromUtf8("ID4_label"))
        self.horizontalLayout_7.addWidget(self.ID4_label)
        self.motorType4_label = QtGui.QLabel(self.layoutWidget1)
        self.motorType4_label.setObjectName(_fromUtf8("motorType4_label"))
        self.horizontalLayout_7.addWidget(self.motorType4_label)
        self.motor4center_label = QtGui.QLabel(self.layoutWidget1)
        self.motor4center_label.setObjectName(_fromUtf8("motor4center_label"))
        self.horizontalLayout_7.addWidget(self.motor4center_label)
        self.motor4Value_spinBox = QtGui.QSpinBox(self.layoutWidget1)
        self.motor4Value_spinBox.setMaximum(4095)
        self.motor4Value_spinBox.setObjectName(_fromUtf8("motor4Value_spinBox"))
        self.horizontalLayout_7.addWidget(self.motor4Value_spinBox)
        self.motor4value_dial = QtGui.QDial(self.layoutWidget1)
        self.motor4value_dial.setMaximum(4095)
        self.motor4value_dial.setObjectName(_fromUtf8("motor4value_dial"))
        self.horizontalLayout_7.addWidget(self.motor4value_dial)
        self.motor4Set_pushButton = QtGui.QPushButton(self.layoutWidget1)
        self.motor4Set_pushButton.setObjectName(_fromUtf8("motor4Set_pushButton"))
        self.horizontalLayout_7.addWidget(self.motor4Set_pushButton)
        self.motor4Get_pushButton = QtGui.QPushButton(self.layoutWidget1)
        self.motor4Get_pushButton.setObjectName(_fromUtf8("motor4Get_pushButton"))
        self.horizontalLayout_7.addWidget(self.motor4Get_pushButton)
        self.motor4DisT_pushButton = QtGui.QPushButton(self.layoutWidget1)
        self.motor4DisT_pushButton.setObjectName(_fromUtf8("motor4DisT_pushButton"))
        self.horizontalLayout_7.addWidget(self.motor4DisT_pushButton)
        self.verticalLayout_5.addLayout(self.horizontalLayout_7)
        self.horizontalLayout_8 = QtGui.QHBoxLayout()
        self.horizontalLayout_8.setObjectName(_fromUtf8("horizontalLayout_8"))
        self.ID5_label = QtGui.QLabel(self.layoutWidget1)
        self.ID5_label.setObjectName(_fromUtf8("ID5_label"))
        self.horizontalLayout_8.addWidget(self.ID5_label)
        self.motorType5_label = QtGui.QLabel(self.layoutWidget1)
        self.motorType5_label.setObjectName(_fromUtf8("motorType5_label"))
        self.horizontalLayout_8.addWidget(self.motorType5_label)
        self.motor5center_label = QtGui.QLabel(self.layoutWidget1)
        self.motor5center_label.setObjectName(_fromUtf8("motor5center_label"))
        self.horizontalLayout_8.addWidget(self.motor5center_label)
        self.motor5Value_spinBox = QtGui.QSpinBox(self.layoutWidget1)
        self.motor5Value_spinBox.setMaximum(4095)
        self.motor5Value_spinBox.setObjectName(_fromUtf8("motor5Value_spinBox"))
        self.horizontalLayout_8.addWidget(self.motor5Value_spinBox)
        self.motor5value_dial = QtGui.QDial(self.layoutWidget1)
        self.motor5value_dial.setMaximum(4095)
        self.motor5value_dial.setObjectName(_fromUtf8("motor5value_dial"))
        self.horizontalLayout_8.addWidget(self.motor5value_dial)
        self.motor5Set_pushButton = QtGui.QPushButton(self.layoutWidget1)
        self.motor5Set_pushButton.setObjectName(_fromUtf8("motor5Set_pushButton"))
        self.horizontalLayout_8.addWidget(self.motor5Set_pushButton)
        self.motor5Get_pushButton = QtGui.QPushButton(self.layoutWidget1)
        self.motor5Get_pushButton.setObjectName(_fromUtf8("motor5Get_pushButton"))
        self.horizontalLayout_8.addWidget(self.motor5Get_pushButton)
        self.motor5DisT_pushButton = QtGui.QPushButton(self.layoutWidget1)
        self.motor5DisT_pushButton.setObjectName(_fromUtf8("motor5DisT_pushButton"))
        self.horizontalLayout_8.addWidget(self.motor5DisT_pushButton)
        self.verticalLayout_5.addLayout(self.horizontalLayout_8)
        self.horizontalLayout_9 = QtGui.QHBoxLayout()
        self.horizontalLayout_9.setObjectName(_fromUtf8("horizontalLayout_9"))
        self.ID6_label = QtGui.QLabel(self.layoutWidget1)
        self.ID6_label.setObjectName(_fromUtf8("ID6_label"))
        self.horizontalLayout_9.addWidget(self.ID6_label)
        self.motorType6_label = QtGui.QLabel(self.layoutWidget1)
        self.motorType6_label.setObjectName(_fromUtf8("motorType6_label"))
        self.horizontalLayout_9.addWidget(self.motorType6_label)
        self.motor6center_label = QtGui.QLabel(self.layoutWidget1)
        self.motor6center_label.setObjectName(_fromUtf8("motor6center_label"))
        self.horizontalLayout_9.addWidget(self.motor6center_label)
        self.motor6Value_spinBox = QtGui.QSpinBox(self.layoutWidget1)
        self.motor6Value_spinBox.setMaximum(4095)
        self.motor6Value_spinBox.setObjectName(_fromUtf8("motor6Value_spinBox"))
        self.horizontalLayout_9.addWidget(self.motor6Value_spinBox)
        self.motor6value_dial = QtGui.QDial(self.layoutWidget1)
        self.motor6value_dial.setMaximum(4095)
        self.motor6value_dial.setObjectName(_fromUtf8("motor6value_dial"))
        self.horizontalLayout_9.addWidget(self.motor6value_dial)
        self.motor6Set_pushButton = QtGui.QPushButton(self.layoutWidget1)
        self.motor6Set_pushButton.setObjectName(_fromUtf8("motor6Set_pushButton"))
        self.horizontalLayout_9.addWidget(self.motor6Set_pushButton)
        self.motor6Get_pushButton = QtGui.QPushButton(self.layoutWidget1)
        self.motor6Get_pushButton.setObjectName(_fromUtf8("motor6Get_pushButton"))
        self.horizontalLayout_9.addWidget(self.motor6Get_pushButton)
        self.motor6DisT_pushButton = QtGui.QPushButton(self.layoutWidget1)
        self.motor6DisT_pushButton.setObjectName(_fromUtf8("motor6DisT_pushButton"))
        self.horizontalLayout_9.addWidget(self.motor6DisT_pushButton)
        self.verticalLayout_5.addLayout(self.horizontalLayout_9)
        self.layoutWidget2 = QtGui.QWidget(Form)
        self.layoutWidget2.setGeometry(QtCore.QRect(10, 30, 371, 51))
        self.layoutWidget2.setObjectName(_fromUtf8("layoutWidget2"))
        self.horizontalLayout = QtGui.QHBoxLayout(self.layoutWidget2)
        self.horizontalLayout.setMargin(0)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.file_label = QtGui.QLabel(self.layoutWidget2)
        self.file_label.setObjectName(_fromUtf8("file_label"))
        self.verticalLayout.addWidget(self.file_label)
        self.play_label = QtGui.QLabel(self.layoutWidget2)
        self.play_label.setObjectName(_fromUtf8("play_label"))
        self.verticalLayout.addWidget(self.play_label)
        self.horizontalLayout.addLayout(self.verticalLayout)
        self.verticalLayout_2 = QtGui.QVBoxLayout()
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.fileName_label = QtGui.QLabel(self.layoutWidget2)
        self.fileName_label.setObjectName(_fromUtf8("fileName_label"))
        self.verticalLayout_2.addWidget(self.fileName_label)
        self.allKeyframe_label = QtGui.QLabel(self.layoutWidget2)
        self.allKeyframe_label.setObjectName(_fromUtf8("allKeyframe_label"))
        self.verticalLayout_2.addWidget(self.allKeyframe_label)
        self.horizontalLayout.addLayout(self.verticalLayout_2)
        self.verticalLayout_3 = QtGui.QVBoxLayout()
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.numOfKeyframe_label = QtGui.QLabel(self.layoutWidget2)
        self.numOfKeyframe_label.setObjectName(_fromUtf8("numOfKeyframe_label"))
        self.verticalLayout_3.addWidget(self.numOfKeyframe_label)
        self.setReady_Button = QtGui.QPushButton(self.layoutWidget2)
        self.setReady_Button.setObjectName(_fromUtf8("setReady_Button"))
        self.verticalLayout_3.addWidget(self.setReady_Button)
        self.horizontalLayout.addLayout(self.verticalLayout_3)
        self.verticalLayout_4 = QtGui.QVBoxLayout()
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.numOfKeyframeStatus_label = QtGui.QLabel(self.layoutWidget2)
        self.numOfKeyframeStatus_label.setObjectName(_fromUtf8("numOfKeyframeStatus_label"))
        self.verticalLayout_4.addWidget(self.numOfKeyframeStatus_label)
        self.playAll_Button = QtGui.QPushButton(self.layoutWidget2)
        self.playAll_Button.setObjectName(_fromUtf8("playAll_Button"))
        self.verticalLayout_4.addWidget(self.playAll_Button)
        self.horizontalLayout.addLayout(self.verticalLayout_4)
        self.layoutWidget3 = QtGui.QWidget(Form)
        self.layoutWidget3.setGeometry(QtCore.QRect(10, 80, 371, 31))
        self.layoutWidget3.setObjectName(_fromUtf8("layoutWidget3"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout(self.layoutWidget3)
        self.horizontalLayout_2.setMargin(0)
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.SelectedKeyframe_label = QtGui.QLabel(self.layoutWidget3)
        self.SelectedKeyframe_label.setObjectName(_fromUtf8("SelectedKeyframe_label"))
        self.horizontalLayout_2.addWidget(self.SelectedKeyframe_label)
        self.keyFrame_comboBox = QtGui.QComboBox(self.layoutWidget3)
        self.keyFrame_comboBox.setObjectName(_fromUtf8("keyFrame_comboBox"))
        self.horizontalLayout_2.addWidget(self.keyFrame_comboBox)
        self.activeKeyframe_checkBox = QtGui.QCheckBox(self.layoutWidget3)
        self.activeKeyframe_checkBox.setEnabled(True)
        self.activeKeyframe_checkBox.setObjectName(_fromUtf8("activeKeyframe_checkBox"))
        self.horizontalLayout_2.addWidget(self.activeKeyframe_checkBox)
        self.play_pushButton = QtGui.QPushButton(self.layoutWidget3)
        self.play_pushButton.setObjectName(_fromUtf8("play_pushButton"))
        self.horizontalLayout_2.addWidget(self.play_pushButton)
        self.layoutWidget4 = QtGui.QWidget(Form)
        self.layoutWidget4.setGeometry(QtCore.QRect(10, 140, 422, 31))
        self.layoutWidget4.setObjectName(_fromUtf8("layoutWidget4"))
        self.horizontalLayout_3 = QtGui.QHBoxLayout(self.layoutWidget4)
        self.horizontalLayout_3.setMargin(0)
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.keyframeTime_label = QtGui.QLabel(self.layoutWidget4)
        self.keyframeTime_label.setObjectName(_fromUtf8("keyframeTime_label"))
        self.horizontalLayout_3.addWidget(self.keyframeTime_label)
        self.keyframeTime_spinBox = QtGui.QSpinBox(self.layoutWidget4)
        self.keyframeTime_spinBox.setObjectName(_fromUtf8("keyframeTime_spinBox"))
        self.horizontalLayout_3.addWidget(self.keyframeTime_spinBox)
        self.setTime_pushButton = QtGui.QPushButton(self.layoutWidget4)
        self.setTime_pushButton.setObjectName(_fromUtf8("setTime_pushButton"))
        self.horizontalLayout_3.addWidget(self.setTime_pushButton)
        self.setAll_pushButton = QtGui.QPushButton(self.layoutWidget4)
        self.setAll_pushButton.setObjectName(_fromUtf8("setAll_pushButton"))
        self.horizontalLayout_3.addWidget(self.setAll_pushButton)
        self.getAll_pushButton = QtGui.QPushButton(self.layoutWidget4)
        self.getAll_pushButton.setObjectName(_fromUtf8("getAll_pushButton"))
        self.horizontalLayout_3.addWidget(self.getAll_pushButton)
        self.disTAll_pushButton = QtGui.QPushButton(self.layoutWidget4)
        self.disTAll_pushButton.setObjectName(_fromUtf8("disTAll_pushButton"))
        self.horizontalLayout_3.addWidget(self.disTAll_pushButton)
        self.horizontalLayoutWidget_3 = QtGui.QWidget(Form)
        self.horizontalLayoutWidget_3.setGeometry(QtCore.QRect(420, 0, 441, 29))
        self.horizontalLayoutWidget_3.setObjectName(_fromUtf8("horizontalLayoutWidget_3"))
        self.horizontalLayout_24 = QtGui.QHBoxLayout(self.horizontalLayoutWidget_3)
        self.horizontalLayout_24.setMargin(0)
        self.horizontalLayout_24.setObjectName(_fromUtf8("horizontalLayout_24"))
        self.comport_comboBox = QtGui.QComboBox(self.horizontalLayoutWidget_3)
        self.comport_comboBox.setObjectName(_fromUtf8("comport_comboBox"))
        self.horizontalLayout_24.addWidget(self.comport_comboBox)
        self.baudrate_comboBox = QtGui.QComboBox(self.horizontalLayoutWidget_3)
        self.baudrate_comboBox.setObjectName(_fromUtf8("baudrate_comboBox"))
        self.horizontalLayout_24.addWidget(self.baudrate_comboBox)
        self.connectionStatus_label = QtGui.QLabel(self.horizontalLayoutWidget_3)
        self.connectionStatus_label.setObjectName(_fromUtf8("connectionStatus_label"))
        self.horizontalLayout_24.addWidget(self.connectionStatus_label)
        self.connect_Button = QtGui.QPushButton(self.horizontalLayoutWidget_3)
        self.connect_Button.setObjectName(_fromUtf8("connect_Button"))
        self.horizontalLayout_24.addWidget(self.connect_Button)
        self.horizontalLayoutWidget_2 = QtGui.QWidget(Form)
        self.horizontalLayoutWidget_2.setGeometry(QtCore.QRect(10, 0, 387, 29))
        self.horizontalLayoutWidget_2.setObjectName(_fromUtf8("horizontalLayoutWidget_2"))
        self.horizontalLayout_23 = QtGui.QHBoxLayout(self.horizontalLayoutWidget_2)
        self.horizontalLayout_23.setMargin(0)
        self.horizontalLayout_23.setObjectName(_fromUtf8("horizontalLayout_23"))
        self.postureName_label = QtGui.QLabel(self.horizontalLayoutWidget_2)
        self.postureName_label.setObjectName(_fromUtf8("postureName_label"))
        self.horizontalLayout_23.addWidget(self.postureName_label)
        self.posture_comboBox = QtGui.QComboBox(self.horizontalLayoutWidget_2)
        self.posture_comboBox.setObjectName(_fromUtf8("posture_comboBox"))
        self.horizontalLayout_23.addWidget(self.posture_comboBox)
        self.loadPosture_pushButton = QtGui.QPushButton(self.horizontalLayoutWidget_2)
        self.loadPosture_pushButton.setObjectName(_fromUtf8("loadPosture_pushButton"))
        self.horizontalLayout_23.addWidget(self.loadPosture_pushButton)
        self.savePosture_pushButton = QtGui.QPushButton(self.horizontalLayoutWidget_2)
        self.savePosture_pushButton.setObjectName(_fromUtf8("savePosture_pushButton"))
        self.horizontalLayout_23.addWidget(self.savePosture_pushButton)
        self.saveCenter_pushButton = QtGui.QPushButton(self.horizontalLayoutWidget_2)
        self.saveCenter_pushButton.setObjectName(_fromUtf8("saveCenter_pushButton"))
        self.horizontalLayout_23.addWidget(self.saveCenter_pushButton)
        self.horizontalLayoutWidget = QtGui.QWidget(Form)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(10, 110, 371, 31))
        self.horizontalLayoutWidget.setObjectName(_fromUtf8("horizontalLayoutWidget"))
        self.horizontalLayout_18 = QtGui.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout_18.setMargin(0)
        self.horizontalLayout_18.setObjectName(_fromUtf8("horizontalLayout_18"))
        self.deleteKeyframe_pushButton = QtGui.QPushButton(self.horizontalLayoutWidget)
        self.deleteKeyframe_pushButton.setObjectName(_fromUtf8("deleteKeyframe_pushButton"))
        self.horizontalLayout_18.addWidget(self.deleteKeyframe_pushButton)
        self.duplicateKeyframe_pushButton = QtGui.QPushButton(self.horizontalLayoutWidget)
        self.duplicateKeyframe_pushButton.setObjectName(_fromUtf8("duplicateKeyframe_pushButton"))
        self.horizontalLayout_18.addWidget(self.duplicateKeyframe_pushButton)
        self.previousSwitchKeyframe_pushButton = QtGui.QPushButton(self.horizontalLayoutWidget)
        self.previousSwitchKeyframe_pushButton.setObjectName(_fromUtf8("previousSwitchKeyframe_pushButton"))
        self.horizontalLayout_18.addWidget(self.previousSwitchKeyframe_pushButton)
        self.nextSwitchKeyframe_pushButton = QtGui.QPushButton(self.horizontalLayoutWidget)
        self.nextSwitchKeyframe_pushButton.setObjectName(_fromUtf8("nextSwitchKeyframe_pushButton"))
        self.horizontalLayout_18.addWidget(self.nextSwitchKeyframe_pushButton)
        self.verticalLayoutWidget_8 = QtGui.QWidget(Form)
        self.verticalLayoutWidget_8.setGeometry(QtCore.QRect(460, 490, 441, 201))
        self.verticalLayoutWidget_8.setObjectName(_fromUtf8("verticalLayoutWidget_8"))
        self.verticalLayout_8 = QtGui.QVBoxLayout(self.verticalLayoutWidget_8)
        self.verticalLayout_8.setMargin(0)
        self.verticalLayout_8.setObjectName(_fromUtf8("verticalLayout_8"))
        self.horizontalLayout_28 = QtGui.QHBoxLayout()
        self.horizontalLayout_28.setObjectName(_fromUtf8("horizontalLayout_28"))
        self.setRArmAll_pushButton = QtGui.QPushButton(self.verticalLayoutWidget_8)
        self.setRArmAll_pushButton.setObjectName(_fromUtf8("setRArmAll_pushButton"))
        self.horizontalLayout_28.addWidget(self.setRArmAll_pushButton)
        self.getRArmAll_pushButton = QtGui.QPushButton(self.verticalLayoutWidget_8)
        self.getRArmAll_pushButton.setObjectName(_fromUtf8("getRArmAll_pushButton"))
        self.horizontalLayout_28.addWidget(self.getRArmAll_pushButton)
        self.disTRArmAll_pushButton = QtGui.QPushButton(self.verticalLayoutWidget_8)
        self.disTRArmAll_pushButton.setObjectName(_fromUtf8("disTRArmAll_pushButton"))
        self.horizontalLayout_28.addWidget(self.disTRArmAll_pushButton)
        self.verticalLayout_8.addLayout(self.horizontalLayout_28)
        self.horizontalLayout_29 = QtGui.QHBoxLayout()
        self.horizontalLayout_29.setObjectName(_fromUtf8("horizontalLayout_29"))
        self.ID31_label = QtGui.QLabel(self.verticalLayoutWidget_8)
        self.ID31_label.setObjectName(_fromUtf8("ID31_label"))
        self.horizontalLayout_29.addWidget(self.ID31_label)
        self.motorType31_label = QtGui.QLabel(self.verticalLayoutWidget_8)
        self.motorType31_label.setObjectName(_fromUtf8("motorType31_label"))
        self.horizontalLayout_29.addWidget(self.motorType31_label)
        self.motor31center_label = QtGui.QLabel(self.verticalLayoutWidget_8)
        self.motor31center_label.setObjectName(_fromUtf8("motor31center_label"))
        self.horizontalLayout_29.addWidget(self.motor31center_label)
        self.motor31Value_spinBox = QtGui.QSpinBox(self.verticalLayoutWidget_8)
        self.motor31Value_spinBox.setMaximum(4095)
        self.motor31Value_spinBox.setObjectName(_fromUtf8("motor31Value_spinBox"))
        self.horizontalLayout_29.addWidget(self.motor31Value_spinBox)
        self.motor31value_dial = QtGui.QDial(self.verticalLayoutWidget_8)
        self.motor31value_dial.setMaximum(4095)
        self.motor31value_dial.setObjectName(_fromUtf8("motor31value_dial"))
        self.horizontalLayout_29.addWidget(self.motor31value_dial)
        self.motor31Set_pushButton = QtGui.QPushButton(self.verticalLayoutWidget_8)
        self.motor31Set_pushButton.setObjectName(_fromUtf8("motor31Set_pushButton"))
        self.horizontalLayout_29.addWidget(self.motor31Set_pushButton)
        self.motor31Get_pushButton = QtGui.QPushButton(self.verticalLayoutWidget_8)
        self.motor31Get_pushButton.setObjectName(_fromUtf8("motor31Get_pushButton"))
        self.horizontalLayout_29.addWidget(self.motor31Get_pushButton)
        self.motor31DisT_pushButton = QtGui.QPushButton(self.verticalLayoutWidget_8)
        self.motor31DisT_pushButton.setObjectName(_fromUtf8("motor31DisT_pushButton"))
        self.horizontalLayout_29.addWidget(self.motor31DisT_pushButton)
        self.verticalLayout_8.addLayout(self.horizontalLayout_29)
        self.horizontalLayout_30 = QtGui.QHBoxLayout()
        self.horizontalLayout_30.setObjectName(_fromUtf8("horizontalLayout_30"))
        self.ID32_label = QtGui.QLabel(self.verticalLayoutWidget_8)
        self.ID32_label.setObjectName(_fromUtf8("ID32_label"))
        self.horizontalLayout_30.addWidget(self.ID32_label)
        self.motorType32_label = QtGui.QLabel(self.verticalLayoutWidget_8)
        self.motorType32_label.setObjectName(_fromUtf8("motorType32_label"))
        self.horizontalLayout_30.addWidget(self.motorType32_label)
        self.motor32center_label = QtGui.QLabel(self.verticalLayoutWidget_8)
        self.motor32center_label.setObjectName(_fromUtf8("motor32center_label"))
        self.horizontalLayout_30.addWidget(self.motor32center_label)
        self.motor32Value_spinBox = QtGui.QSpinBox(self.verticalLayoutWidget_8)
        self.motor32Value_spinBox.setMaximum(4095)
        self.motor32Value_spinBox.setObjectName(_fromUtf8("motor32Value_spinBox"))
        self.horizontalLayout_30.addWidget(self.motor32Value_spinBox)
        self.motor32value_dial = QtGui.QDial(self.verticalLayoutWidget_8)
        self.motor32value_dial.setMaximum(4095)
        self.motor32value_dial.setObjectName(_fromUtf8("motor32value_dial"))
        self.horizontalLayout_30.addWidget(self.motor32value_dial)
        self.motor32Set_pushButton = QtGui.QPushButton(self.verticalLayoutWidget_8)
        self.motor32Set_pushButton.setObjectName(_fromUtf8("motor32Set_pushButton"))
        self.horizontalLayout_30.addWidget(self.motor32Set_pushButton)
        self.motor32Get_pushButton = QtGui.QPushButton(self.verticalLayoutWidget_8)
        self.motor32Get_pushButton.setObjectName(_fromUtf8("motor32Get_pushButton"))
        self.horizontalLayout_30.addWidget(self.motor32Get_pushButton)
        self.motor32DisT_pushButton = QtGui.QPushButton(self.verticalLayoutWidget_8)
        self.motor32DisT_pushButton.setObjectName(_fromUtf8("motor32DisT_pushButton"))
        self.horizontalLayout_30.addWidget(self.motor32DisT_pushButton)
        self.verticalLayout_8.addLayout(self.horizontalLayout_30)
        self.horizontalLayout_31 = QtGui.QHBoxLayout()
        self.horizontalLayout_31.setObjectName(_fromUtf8("horizontalLayout_31"))
        self.ID33_label = QtGui.QLabel(self.verticalLayoutWidget_8)
        self.ID33_label.setObjectName(_fromUtf8("ID33_label"))
        self.horizontalLayout_31.addWidget(self.ID33_label)
        self.motorType33_label = QtGui.QLabel(self.verticalLayoutWidget_8)
        self.motorType33_label.setObjectName(_fromUtf8("motorType33_label"))
        self.horizontalLayout_31.addWidget(self.motorType33_label)
        self.motor33center_label = QtGui.QLabel(self.verticalLayoutWidget_8)
        self.motor33center_label.setObjectName(_fromUtf8("motor33center_label"))
        self.horizontalLayout_31.addWidget(self.motor33center_label)
        self.motor33Value_spinBox = QtGui.QSpinBox(self.verticalLayoutWidget_8)
        self.motor33Value_spinBox.setMaximum(4095)
        self.motor33Value_spinBox.setObjectName(_fromUtf8("motor33Value_spinBox"))
        self.horizontalLayout_31.addWidget(self.motor33Value_spinBox)
        self.motor33value_dial = QtGui.QDial(self.verticalLayoutWidget_8)
        self.motor33value_dial.setMaximum(4095)
        self.motor33value_dial.setObjectName(_fromUtf8("motor33value_dial"))
        self.horizontalLayout_31.addWidget(self.motor33value_dial)
        self.motor33Set_pushButton = QtGui.QPushButton(self.verticalLayoutWidget_8)
        self.motor33Set_pushButton.setObjectName(_fromUtf8("motor33Set_pushButton"))
        self.horizontalLayout_31.addWidget(self.motor33Set_pushButton)
        self.motor33Get_pushButton = QtGui.QPushButton(self.verticalLayoutWidget_8)
        self.motor33Get_pushButton.setObjectName(_fromUtf8("motor33Get_pushButton"))
        self.horizontalLayout_31.addWidget(self.motor33Get_pushButton)
        self.motor33DisT_pushButton = QtGui.QPushButton(self.verticalLayoutWidget_8)
        self.motor33DisT_pushButton.setObjectName(_fromUtf8("motor33DisT_pushButton"))
        self.horizontalLayout_31.addWidget(self.motor33DisT_pushButton)
        self.verticalLayout_8.addLayout(self.horizontalLayout_31)
        self.horizontalLayout_32 = QtGui.QHBoxLayout()
        self.horizontalLayout_32.setObjectName(_fromUtf8("horizontalLayout_32"))
        self.ID34_label = QtGui.QLabel(self.verticalLayoutWidget_8)
        self.ID34_label.setObjectName(_fromUtf8("ID34_label"))
        self.horizontalLayout_32.addWidget(self.ID34_label)
        self.motorType34_label = QtGui.QLabel(self.verticalLayoutWidget_8)
        self.motorType34_label.setObjectName(_fromUtf8("motorType34_label"))
        self.horizontalLayout_32.addWidget(self.motorType34_label)
        self.motor34center_label = QtGui.QLabel(self.verticalLayoutWidget_8)
        self.motor34center_label.setObjectName(_fromUtf8("motor34center_label"))
        self.horizontalLayout_32.addWidget(self.motor34center_label)
        self.motor34Value_spinBox = QtGui.QSpinBox(self.verticalLayoutWidget_8)
        self.motor34Value_spinBox.setMaximum(4095)
        self.motor34Value_spinBox.setObjectName(_fromUtf8("motor34Value_spinBox"))
        self.horizontalLayout_32.addWidget(self.motor34Value_spinBox)
        self.motor34value_dial = QtGui.QDial(self.verticalLayoutWidget_8)
        self.motor34value_dial.setMaximum(4095)
        self.motor34value_dial.setObjectName(_fromUtf8("motor34value_dial"))
        self.horizontalLayout_32.addWidget(self.motor34value_dial)
        self.motor34Set_pushButton = QtGui.QPushButton(self.verticalLayoutWidget_8)
        self.motor34Set_pushButton.setObjectName(_fromUtf8("motor34Set_pushButton"))
        self.horizontalLayout_32.addWidget(self.motor34Set_pushButton)
        self.motor34Get_pushButton = QtGui.QPushButton(self.verticalLayoutWidget_8)
        self.motor34Get_pushButton.setObjectName(_fromUtf8("motor34Get_pushButton"))
        self.horizontalLayout_32.addWidget(self.motor34Get_pushButton)
        self.motor34DisT_pushButton = QtGui.QPushButton(self.verticalLayoutWidget_8)
        self.motor34DisT_pushButton.setObjectName(_fromUtf8("motor34DisT_pushButton"))
        self.horizontalLayout_32.addWidget(self.motor34DisT_pushButton)
        self.verticalLayout_8.addLayout(self.horizontalLayout_32)
        self.verticalLayoutWidget_9 = QtGui.QWidget(Form)
        self.verticalLayoutWidget_9.setGeometry(QtCore.QRect(460, 30, 441, 151))
        self.verticalLayoutWidget_9.setObjectName(_fromUtf8("verticalLayoutWidget_9"))
        self.verticalLayout_9 = QtGui.QVBoxLayout(self.verticalLayoutWidget_9)
        self.verticalLayout_9.setMargin(0)
        self.verticalLayout_9.setObjectName(_fromUtf8("verticalLayout_9"))
        self.horizontalLayout_33 = QtGui.QHBoxLayout()
        self.horizontalLayout_33.setObjectName(_fromUtf8("horizontalLayout_33"))
        self.setHAll_pushButton = QtGui.QPushButton(self.verticalLayoutWidget_9)
        self.setHAll_pushButton.setObjectName(_fromUtf8("setHAll_pushButton"))
        self.horizontalLayout_33.addWidget(self.setHAll_pushButton)
        self.getHAll_pushButton = QtGui.QPushButton(self.verticalLayoutWidget_9)
        self.getHAll_pushButton.setObjectName(_fromUtf8("getHAll_pushButton"))
        self.horizontalLayout_33.addWidget(self.getHAll_pushButton)
        self.disTHAll_pushButton = QtGui.QPushButton(self.verticalLayoutWidget_9)
        self.disTHAll_pushButton.setObjectName(_fromUtf8("disTHAll_pushButton"))
        self.horizontalLayout_33.addWidget(self.disTHAll_pushButton)
        self.verticalLayout_9.addLayout(self.horizontalLayout_33)
        self.horizontalLayout_34 = QtGui.QHBoxLayout()
        self.horizontalLayout_34.setObjectName(_fromUtf8("horizontalLayout_34"))
        self.ID41_label = QtGui.QLabel(self.verticalLayoutWidget_9)
        self.ID41_label.setObjectName(_fromUtf8("ID41_label"))
        self.horizontalLayout_34.addWidget(self.ID41_label)
        self.motorType41_label = QtGui.QLabel(self.verticalLayoutWidget_9)
        self.motorType41_label.setObjectName(_fromUtf8("motorType41_label"))
        self.horizontalLayout_34.addWidget(self.motorType41_label)
        self.motor41center_label = QtGui.QLabel(self.verticalLayoutWidget_9)
        self.motor41center_label.setObjectName(_fromUtf8("motor41center_label"))
        self.horizontalLayout_34.addWidget(self.motor41center_label)
        self.motor41Value_spinBox = QtGui.QSpinBox(self.verticalLayoutWidget_9)
        self.motor41Value_spinBox.setMaximum(4095)
        self.motor41Value_spinBox.setObjectName(_fromUtf8("motor41Value_spinBox"))
        self.horizontalLayout_34.addWidget(self.motor41Value_spinBox)
        self.motor41value_dial = QtGui.QDial(self.verticalLayoutWidget_9)
        self.motor41value_dial.setMaximum(4095)
        self.motor41value_dial.setObjectName(_fromUtf8("motor41value_dial"))
        self.horizontalLayout_34.addWidget(self.motor41value_dial)
        self.motor41Set_pushButton = QtGui.QPushButton(self.verticalLayoutWidget_9)
        self.motor41Set_pushButton.setObjectName(_fromUtf8("motor41Set_pushButton"))
        self.horizontalLayout_34.addWidget(self.motor41Set_pushButton)
        self.motor41Get_pushButton = QtGui.QPushButton(self.verticalLayoutWidget_9)
        self.motor41Get_pushButton.setObjectName(_fromUtf8("motor41Get_pushButton"))
        self.horizontalLayout_34.addWidget(self.motor41Get_pushButton)
        self.motor41DisT_pushButton = QtGui.QPushButton(self.verticalLayoutWidget_9)
        self.motor41DisT_pushButton.setObjectName(_fromUtf8("motor41DisT_pushButton"))
        self.horizontalLayout_34.addWidget(self.motor41DisT_pushButton)
        self.verticalLayout_9.addLayout(self.horizontalLayout_34)
        self.horizontalLayout_35 = QtGui.QHBoxLayout()
        self.horizontalLayout_35.setObjectName(_fromUtf8("horizontalLayout_35"))
        self.ID42_label = QtGui.QLabel(self.verticalLayoutWidget_9)
        self.ID42_label.setObjectName(_fromUtf8("ID42_label"))
        self.horizontalLayout_35.addWidget(self.ID42_label)
        self.motorType42_label = QtGui.QLabel(self.verticalLayoutWidget_9)
        self.motorType42_label.setObjectName(_fromUtf8("motorType42_label"))
        self.horizontalLayout_35.addWidget(self.motorType42_label)
        self.motor42center_label = QtGui.QLabel(self.verticalLayoutWidget_9)
        self.motor42center_label.setObjectName(_fromUtf8("motor42center_label"))
        self.horizontalLayout_35.addWidget(self.motor42center_label)
        self.motor42Value_spinBox = QtGui.QSpinBox(self.verticalLayoutWidget_9)
        self.motor42Value_spinBox.setMaximum(4095)
        self.motor42Value_spinBox.setObjectName(_fromUtf8("motor42Value_spinBox"))
        self.horizontalLayout_35.addWidget(self.motor42Value_spinBox)
        self.motor42value_dial = QtGui.QDial(self.verticalLayoutWidget_9)
        self.motor42value_dial.setMaximum(4095)
        self.motor42value_dial.setObjectName(_fromUtf8("motor42value_dial"))
        self.horizontalLayout_35.addWidget(self.motor42value_dial)
        self.motor42Set_pushButton = QtGui.QPushButton(self.verticalLayoutWidget_9)
        self.motor42Set_pushButton.setObjectName(_fromUtf8("motor42Set_pushButton"))
        self.horizontalLayout_35.addWidget(self.motor42Set_pushButton)
        self.motor42Get_pushButton = QtGui.QPushButton(self.verticalLayoutWidget_9)
        self.motor42Get_pushButton.setObjectName(_fromUtf8("motor42Get_pushButton"))
        self.horizontalLayout_35.addWidget(self.motor42Get_pushButton)
        self.motor42DisT_pushButton = QtGui.QPushButton(self.verticalLayoutWidget_9)
        self.motor42DisT_pushButton.setObjectName(_fromUtf8("motor42DisT_pushButton"))
        self.horizontalLayout_35.addWidget(self.motor42DisT_pushButton)
        self.verticalLayout_9.addLayout(self.horizontalLayout_35)
        self.horizontalLayout_36 = QtGui.QHBoxLayout()
        self.horizontalLayout_36.setObjectName(_fromUtf8("horizontalLayout_36"))
        self.ID43_label = QtGui.QLabel(self.verticalLayoutWidget_9)
        self.ID43_label.setObjectName(_fromUtf8("ID43_label"))
        self.horizontalLayout_36.addWidget(self.ID43_label)
        self.motorType43_label = QtGui.QLabel(self.verticalLayoutWidget_9)
        self.motorType43_label.setObjectName(_fromUtf8("motorType43_label"))
        self.horizontalLayout_36.addWidget(self.motorType43_label)
        self.motor43center_label = QtGui.QLabel(self.verticalLayoutWidget_9)
        self.motor43center_label.setObjectName(_fromUtf8("motor43center_label"))
        self.horizontalLayout_36.addWidget(self.motor43center_label)
        self.motor43Value_spinBox = QtGui.QSpinBox(self.verticalLayoutWidget_9)
        self.motor43Value_spinBox.setMaximum(4095)
        self.motor43Value_spinBox.setObjectName(_fromUtf8("motor43Value_spinBox"))
        self.horizontalLayout_36.addWidget(self.motor43Value_spinBox)
        self.motor43value_dial = QtGui.QDial(self.verticalLayoutWidget_9)
        self.motor43value_dial.setMaximum(4095)
        self.motor43value_dial.setObjectName(_fromUtf8("motor43value_dial"))
        self.horizontalLayout_36.addWidget(self.motor43value_dial)
        self.motor43Set_pushButton = QtGui.QPushButton(self.verticalLayoutWidget_9)
        self.motor43Set_pushButton.setObjectName(_fromUtf8("motor43Set_pushButton"))
        self.horizontalLayout_36.addWidget(self.motor43Set_pushButton)
        self.motor43Get_pushButton = QtGui.QPushButton(self.verticalLayoutWidget_9)
        self.motor43Get_pushButton.setObjectName(_fromUtf8("motor43Get_pushButton"))
        self.horizontalLayout_36.addWidget(self.motor43Get_pushButton)
        self.motor43DisT_pushButton = QtGui.QPushButton(self.verticalLayoutWidget_9)
        self.motor43DisT_pushButton.setObjectName(_fromUtf8("motor43DisT_pushButton"))
        self.horizontalLayout_36.addWidget(self.motor43DisT_pushButton)
        self.verticalLayout_9.addLayout(self.horizontalLayout_36)

        self.retranslateUi(Form)
        QtCore.QObject.connect(self.motor1value_dial, QtCore.SIGNAL(_fromUtf8("valueChanged(int)")), self.motor1Value_spinBox.setValue)
        QtCore.QObject.connect(self.motor1Value_spinBox, QtCore.SIGNAL(_fromUtf8("valueChanged(int)")), self.motor1value_dial.setValue)
        QtCore.QObject.connect(self.motor2value_dial, QtCore.SIGNAL(_fromUtf8("valueChanged(int)")), self.motor2Value_spinBox.setValue)
        QtCore.QObject.connect(self.motor2Value_spinBox, QtCore.SIGNAL(_fromUtf8("valueChanged(int)")), self.motor2value_dial.setValue)
        QtCore.QObject.connect(self.motor3value_dial, QtCore.SIGNAL(_fromUtf8("valueChanged(int)")), self.motor3Value_spinBox.setValue)
        QtCore.QObject.connect(self.motor3Value_spinBox, QtCore.SIGNAL(_fromUtf8("valueChanged(int)")), self.motor3value_dial.setValue)
        QtCore.QObject.connect(self.motor4value_dial, QtCore.SIGNAL(_fromUtf8("valueChanged(int)")), self.motor4Value_spinBox.setValue)
        QtCore.QObject.connect(self.motor4Value_spinBox, QtCore.SIGNAL(_fromUtf8("valueChanged(int)")), self.motor4value_dial.setValue)
        QtCore.QObject.connect(self.motor5value_dial, QtCore.SIGNAL(_fromUtf8("valueChanged(int)")), self.motor5Value_spinBox.setValue)
        QtCore.QObject.connect(self.motor5Value_spinBox, QtCore.SIGNAL(_fromUtf8("valueChanged(int)")), self.motor5value_dial.setValue)
        QtCore.QObject.connect(self.motor6value_dial, QtCore.SIGNAL(_fromUtf8("valueChanged(int)")), self.motor6Value_spinBox.setValue)
        QtCore.QObject.connect(self.motor6Value_spinBox, QtCore.SIGNAL(_fromUtf8("valueChanged(int)")), self.motor6value_dial.setValue)
        QtCore.QObject.connect(self.motor11value_dial, QtCore.SIGNAL(_fromUtf8("valueChanged(int)")), self.motor11Value_spinBox.setValue)
        QtCore.QObject.connect(self.motor11Value_spinBox, QtCore.SIGNAL(_fromUtf8("valueChanged(int)")), self.motor11value_dial.setValue)
        QtCore.QObject.connect(self.motor12value_dial, QtCore.SIGNAL(_fromUtf8("valueChanged(int)")), self.motor12Value_spinBox.setValue)
        QtCore.QObject.connect(self.motor12Value_spinBox, QtCore.SIGNAL(_fromUtf8("valueChanged(int)")), self.motor12value_dial.setValue)
        QtCore.QObject.connect(self.motor13value_dial, QtCore.SIGNAL(_fromUtf8("valueChanged(int)")), self.motor13Value_spinBox.setValue)
        QtCore.QObject.connect(self.motor13Value_spinBox, QtCore.SIGNAL(_fromUtf8("valueChanged(int)")), self.motor13value_dial.setValue)
        QtCore.QObject.connect(self.motor14value_dial, QtCore.SIGNAL(_fromUtf8("valueChanged(int)")), self.motor14Value_spinBox.setValue)
        QtCore.QObject.connect(self.motor14Value_spinBox, QtCore.SIGNAL(_fromUtf8("valueChanged(int)")), self.motor14value_dial.setValue)
        QtCore.QObject.connect(self.motor15value_dial, QtCore.SIGNAL(_fromUtf8("valueChanged(int)")), self.motor15Value_spinBox.setValue)
        QtCore.QObject.connect(self.motor15Value_spinBox, QtCore.SIGNAL(_fromUtf8("valueChanged(int)")), self.motor15value_dial.setValue)
        QtCore.QObject.connect(self.motor16value_dial, QtCore.SIGNAL(_fromUtf8("valueChanged(int)")), self.motor16Value_spinBox.setValue)
        QtCore.QObject.connect(self.motor16Value_spinBox, QtCore.SIGNAL(_fromUtf8("valueChanged(int)")), self.motor16value_dial.setValue)
        QtCore.QObject.connect(self.motor23value_dial, QtCore.SIGNAL(_fromUtf8("valueChanged(int)")), self.motor23Value_spinBox.setValue)
        QtCore.QObject.connect(self.motor23Value_spinBox, QtCore.SIGNAL(_fromUtf8("valueChanged(int)")), self.motor23value_dial.setValue)
        QtCore.QObject.connect(self.motor21value_dial, QtCore.SIGNAL(_fromUtf8("valueChanged(int)")), self.motor21Value_spinBox.setValue)
        QtCore.QObject.connect(self.motor21Value_spinBox, QtCore.SIGNAL(_fromUtf8("valueChanged(int)")), self.motor21value_dial.setValue)
        QtCore.QObject.connect(self.motor22value_dial, QtCore.SIGNAL(_fromUtf8("valueChanged(int)")), self.motor22Value_spinBox.setValue)
        QtCore.QObject.connect(self.motor22Value_spinBox, QtCore.SIGNAL(_fromUtf8("valueChanged(int)")), self.motor22value_dial.setValue)
        QtCore.QObject.connect(self.motor24value_dial, QtCore.SIGNAL(_fromUtf8("valueChanged(int)")), self.motor24Value_spinBox.setValue)
        QtCore.QObject.connect(self.motor24Value_spinBox, QtCore.SIGNAL(_fromUtf8("valueChanged(int)")), self.motor24value_dial.setValue)
        QtCore.QObject.connect(self.motor41Value_spinBox, QtCore.SIGNAL(_fromUtf8("valueChanged(int)")), self.motor41value_dial.setValue)
        QtCore.QObject.connect(self.motor41value_dial, QtCore.SIGNAL(_fromUtf8("valueChanged(int)")), self.motor41Value_spinBox.setValue)
        QtCore.QObject.connect(self.motor42Value_spinBox, QtCore.SIGNAL(_fromUtf8("valueChanged(int)")), self.motor42value_dial.setValue)
        QtCore.QObject.connect(self.motor42value_dial, QtCore.SIGNAL(_fromUtf8("valueChanged(int)")), self.motor42Value_spinBox.setValue)
        QtCore.QObject.connect(self.motor43Value_spinBox, QtCore.SIGNAL(_fromUtf8("valueChanged(int)")), self.motor43value_dial.setValue)
        QtCore.QObject.connect(self.motor43value_dial, QtCore.SIGNAL(_fromUtf8("valueChanged(int)")), self.motor43Value_spinBox.setValue)
        QtCore.QObject.connect(self.motor31Value_spinBox, QtCore.SIGNAL(_fromUtf8("valueChanged(int)")), self.motor31value_dial.setValue)
        QtCore.QObject.connect(self.motor31value_dial, QtCore.SIGNAL(_fromUtf8("valueChanged(int)")), self.motor31Value_spinBox.setValue)
        QtCore.QObject.connect(self.motor32Value_spinBox, QtCore.SIGNAL(_fromUtf8("valueChanged(int)")), self.motor32value_dial.setValue)
        QtCore.QObject.connect(self.motor32value_dial, QtCore.SIGNAL(_fromUtf8("valueChanged(int)")), self.motor32Value_spinBox.setValue)
        QtCore.QObject.connect(self.motor33Value_spinBox, QtCore.SIGNAL(_fromUtf8("valueChanged(int)")), self.motor33value_dial.setValue)
        QtCore.QObject.connect(self.motor33value_dial, QtCore.SIGNAL(_fromUtf8("valueChanged(int)")), self.motor33Value_spinBox.setValue)
        QtCore.QObject.connect(self.motor34Value_spinBox, QtCore.SIGNAL(_fromUtf8("valueChanged(int)")), self.motor34value_dial.setValue)
        QtCore.QObject.connect(self.motor34value_dial, QtCore.SIGNAL(_fromUtf8("valueChanged(int)")), self.motor34Value_spinBox.setValue)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        Form.setWindowTitle(_translate("Form", "Form", None))
        self.setLArmAll_pushButton.setText(_translate("Form", "Set L Arm All", None))
        self.getLArmAll_pushButton.setText(_translate("Form", "Get L Arm All", None))
        self.disTLArmAll_pushButton.setText(_translate("Form", "DisT L Arm All", None))
        self.ID21_label.setText(_translate("Form", "ID21", None))
        self.motorType21_label.setText(_translate("Form", "MX", None))
        self.motor21center_label.setText(_translate("Form", "2048", None))
        self.motor21Set_pushButton.setText(_translate("Form", "Set", None))
        self.motor21Get_pushButton.setText(_translate("Form", "Get", None))
        self.motor21DisT_pushButton.setText(_translate("Form", "DisT", None))
        self.ID22_label.setText(_translate("Form", "ID22", None))
        self.motorType22_label.setText(_translate("Form", "MX", None))
        self.motor22center_label.setText(_translate("Form", "2048", None))
        self.motor22Set_pushButton.setText(_translate("Form", "Set", None))
        self.motor22Get_pushButton.setText(_translate("Form", "Get", None))
        self.motor22DisT_pushButton.setText(_translate("Form", "DisT", None))
        self.ID23_label.setText(_translate("Form", "ID23", None))
        self.motorType23_label.setText(_translate("Form", "MX", None))
        self.motor23center_label.setText(_translate("Form", "2048", None))
        self.motor23Set_pushButton.setText(_translate("Form", "Set", None))
        self.motor23Get_pushButton.setText(_translate("Form", "Get", None))
        self.motor23DisT_pushButton.setText(_translate("Form", "DisT", None))
        self.ID24_label.setText(_translate("Form", "ID24", None))
        self.motorType24_label.setText(_translate("Form", "MX", None))
        self.motor24center_label.setText(_translate("Form", "2048", None))
        self.motor24Set_pushButton.setText(_translate("Form", "Set", None))
        self.motor24Get_pushButton.setText(_translate("Form", "Get", None))
        self.motor24DisT_pushButton.setText(_translate("Form", "DisT", None))
        self.setRAll_pushButton.setText(_translate("Form", "Set R All", None))
        self.getRAll_pushButton.setText(_translate("Form", "Get R All", None))
        self.disTRAll_pushButton.setText(_translate("Form", "DisT R All", None))
        self.ID11_label.setText(_translate("Form", "ID11", None))
        self.motorType11_label.setText(_translate("Form", "MX", None))
        self.motor11center_label.setText(_translate("Form", "2048", None))
        self.motor11Set_pushButton.setText(_translate("Form", "Set", None))
        self.motor11Get_pushButton.setText(_translate("Form", "Get", None))
        self.motor11DisT_pushButton.setText(_translate("Form", "DisT", None))
        self.ID12_label.setText(_translate("Form", "ID12", None))
        self.motorType12_label.setText(_translate("Form", "MX", None))
        self.motor12center_label.setText(_translate("Form", "2048", None))
        self.motor12Set_pushButton.setText(_translate("Form", "Set", None))
        self.motor12Get_pushButton.setText(_translate("Form", "Get", None))
        self.motor12DisT_pushButton.setText(_translate("Form", "DisT", None))
        self.ID13_label.setText(_translate("Form", "ID13", None))
        self.motorType13_label.setText(_translate("Form", "MX", None))
        self.motor13center_label.setText(_translate("Form", "2048", None))
        self.motor13Set_pushButton.setText(_translate("Form", "Set", None))
        self.motor13Get_pushButton.setText(_translate("Form", "Get", None))
        self.motor13DisT_pushButton.setText(_translate("Form", "DisT", None))
        self.ID14_label.setText(_translate("Form", "ID14", None))
        self.motorType14_label.setText(_translate("Form", "MX", None))
        self.motor14center_label.setText(_translate("Form", "2048", None))
        self.motor14Set_pushButton.setText(_translate("Form", "Set", None))
        self.motor14Get_pushButton.setText(_translate("Form", "Get", None))
        self.motor14DisT_pushButton.setText(_translate("Form", "DisT", None))
        self.ID15_label.setText(_translate("Form", "ID15", None))
        self.motorType15_label.setText(_translate("Form", "MX", None))
        self.motor15center_label.setText(_translate("Form", "2048", None))
        self.motor15Set_pushButton.setText(_translate("Form", "Set", None))
        self.motor15Get_pushButton.setText(_translate("Form", "Get", None))
        self.motor15DisT_pushButton.setText(_translate("Form", "DisT", None))
        self.ID7_label_.setText(_translate("Form", "ID16", None))
        self.motorType16_label.setText(_translate("Form", "MX", None))
        self.motor16center_label.setText(_translate("Form", "2048", None))
        self.motor16Set_pushButton.setText(_translate("Form", "Set", None))
        self.motor16Get_pushButton.setText(_translate("Form", "Get", None))
        self.motor16DisT_pushButton.setText(_translate("Form", "DisT", None))
        self.setLAll_pushButton.setText(_translate("Form", "Set L All", None))
        self.getLAll_pushButton.setText(_translate("Form", "Get L All", None))
        self.disTLAll_pushButton.setText(_translate("Form", "DisT L All", None))
        self.ID1_label.setText(_translate("Form", "ID1", None))
        self.motorType1_label.setText(_translate("Form", "MX", None))
        self.motor1center_label.setText(_translate("Form", "2048", None))
        self.motor1Set_pushButton.setText(_translate("Form", "Set", None))
        self.motor1Get_pushButton.setText(_translate("Form", "Get", None))
        self.motor1DisT_pushButton.setText(_translate("Form", "DisT", None))
        self.ID2_label.setText(_translate("Form", "ID2", None))
        self.motorType2_label.setText(_translate("Form", "MX", None))
        self.motor2center_label.setText(_translate("Form", "2048", None))
        self.motor2Set_pushButton.setText(_translate("Form", "Set", None))
        self.motor2Get_pushButton.setText(_translate("Form", "Get", None))
        self.motor2DisT_pushButton.setText(_translate("Form", "DisT", None))
        self.ID3_label.setText(_translate("Form", "ID3", None))
        self.motorType3_label.setText(_translate("Form", "MX", None))
        self.motor3center_label.setText(_translate("Form", "2048", None))
        self.motor3Set_pushButton.setText(_translate("Form", "Set", None))
        self.motor3Get_pushButton.setText(_translate("Form", "Get", None))
        self.motor3DisT_pushButton.setText(_translate("Form", "DisT", None))
        self.ID4_label.setText(_translate("Form", "ID4", None))
        self.motorType4_label.setText(_translate("Form", "MX", None))
        self.motor4center_label.setText(_translate("Form", "2048", None))
        self.motor4Set_pushButton.setText(_translate("Form", "Set", None))
        self.motor4Get_pushButton.setText(_translate("Form", "Get", None))
        self.motor4DisT_pushButton.setText(_translate("Form", "DisT", None))
        self.ID5_label.setText(_translate("Form", "ID5", None))
        self.motorType5_label.setText(_translate("Form", "MX", None))
        self.motor5center_label.setText(_translate("Form", "2048", None))
        self.motor5Set_pushButton.setText(_translate("Form", "Set", None))
        self.motor5Get_pushButton.setText(_translate("Form", "Get", None))
        self.motor5DisT_pushButton.setText(_translate("Form", "DisT", None))
        self.ID6_label.setText(_translate("Form", "ID6", None))
        self.motorType6_label.setText(_translate("Form", "MX", None))
        self.motor6center_label.setText(_translate("Form", "2048", None))
        self.motor6Set_pushButton.setText(_translate("Form", "Set", None))
        self.motor6Get_pushButton.setText(_translate("Form", "Get", None))
        self.motor6DisT_pushButton.setText(_translate("Form", "DisT", None))
        self.file_label.setText(_translate("Form", "File::", None))
        self.play_label.setText(_translate("Form", "Play", None))
        self.fileName_label.setText(_translate("Form", "File Name", None))
        self.allKeyframe_label.setText(_translate("Form", "All Keyframe", None))
        self.numOfKeyframe_label.setText(_translate("Form", "Number of Keyframe", None))
        self.setReady_Button.setText(_translate("Form", "Set Ready", None))
        self.numOfKeyframeStatus_label.setText(_translate("Form", "0", None))
        self.playAll_Button.setText(_translate("Form", "Play All", None))
        self.SelectedKeyframe_label.setText(_translate("Form", "Selected Keyframe", None))
        self.activeKeyframe_checkBox.setText(_translate("Form", "Active Keyframe", None))
        self.play_pushButton.setText(_translate("Form", "Play", None))
        self.keyframeTime_label.setText(_translate("Form", "KF Time =", None))
        self.setTime_pushButton.setText(_translate("Form", "Set Time", None))
        self.setAll_pushButton.setText(_translate("Form", "Set All", None))
        self.getAll_pushButton.setText(_translate("Form", "Get All", None))
        self.disTAll_pushButton.setText(_translate("Form", "DisT All", None))
        self.connectionStatus_label.setText(_translate("Form", "connection Status", None))
        self.connect_Button.setText(_translate("Form", "Connect", None))
        self.postureName_label.setText(_translate("Form", "Posture Name", None))
        self.loadPosture_pushButton.setText(_translate("Form", "Load", None))
        self.savePosture_pushButton.setText(_translate("Form", "Save", None))
        self.saveCenter_pushButton.setText(_translate("Form", "Save Center", None))
        self.deleteKeyframe_pushButton.setText(_translate("Form", "Delete", None))
        self.duplicateKeyframe_pushButton.setText(_translate("Form", "Duplicate", None))
        self.previousSwitchKeyframe_pushButton.setText(_translate("Form", "Previous Switch", None))
        self.nextSwitchKeyframe_pushButton.setText(_translate("Form", "Next Switch", None))
        self.setRArmAll_pushButton.setText(_translate("Form", "Set R Arm All", None))
        self.getRArmAll_pushButton.setText(_translate("Form", "Get R Arm All", None))
        self.disTRArmAll_pushButton.setText(_translate("Form", "DisT R Arm All", None))
        self.ID31_label.setText(_translate("Form", "ID31", None))
        self.motorType31_label.setText(_translate("Form", "MX", None))
        self.motor31center_label.setText(_translate("Form", "2048", None))
        self.motor31Set_pushButton.setText(_translate("Form", "Set", None))
        self.motor31Get_pushButton.setText(_translate("Form", "Get", None))
        self.motor31DisT_pushButton.setText(_translate("Form", "DisT", None))
        self.ID32_label.setText(_translate("Form", "ID32", None))
        self.motorType32_label.setText(_translate("Form", "MX", None))
        self.motor32center_label.setText(_translate("Form", "2048", None))
        self.motor32Set_pushButton.setText(_translate("Form", "Set", None))
        self.motor32Get_pushButton.setText(_translate("Form", "Get", None))
        self.motor32DisT_pushButton.setText(_translate("Form", "DisT", None))
        self.ID33_label.setText(_translate("Form", "ID33", None))
        self.motorType33_label.setText(_translate("Form", "MX", None))
        self.motor33center_label.setText(_translate("Form", "2048", None))
        self.motor33Set_pushButton.setText(_translate("Form", "Set", None))
        self.motor33Get_pushButton.setText(_translate("Form", "Get", None))
        self.motor33DisT_pushButton.setText(_translate("Form", "DisT", None))
        self.ID34_label.setText(_translate("Form", "ID34", None))
        self.motorType34_label.setText(_translate("Form", "MX", None))
        self.motor34center_label.setText(_translate("Form", "2048", None))
        self.motor34Set_pushButton.setText(_translate("Form", "Set", None))
        self.motor34Get_pushButton.setText(_translate("Form", "Get", None))
        self.motor34DisT_pushButton.setText(_translate("Form", "DisT", None))
        self.setHAll_pushButton.setText(_translate("Form", "Set H All", None))
        self.getHAll_pushButton.setText(_translate("Form", "Get H All", None))
        self.disTHAll_pushButton.setText(_translate("Form", "DisT H All", None))
        self.ID41_label.setText(_translate("Form", "ID41", None))
        self.motorType41_label.setText(_translate("Form", "MX", None))
        self.motor41center_label.setText(_translate("Form", "2048", None))
        self.motor41Set_pushButton.setText(_translate("Form", "Set", None))
        self.motor41Get_pushButton.setText(_translate("Form", "Get", None))
        self.motor41DisT_pushButton.setText(_translate("Form", "DisT", None))
        self.ID42_label.setText(_translate("Form", "ID42", None))
        self.motorType42_label.setText(_translate("Form", "MX", None))
        self.motor42center_label.setText(_translate("Form", "2048", None))
        self.motor42Set_pushButton.setText(_translate("Form", "Set", None))
        self.motor42Get_pushButton.setText(_translate("Form", "Get", None))
        self.motor42DisT_pushButton.setText(_translate("Form", "DisT", None))
        self.ID43_label.setText(_translate("Form", "ID43", None))
        self.motorType43_label.setText(_translate("Form", "MX", None))
        self.motor43center_label.setText(_translate("Form", "2048", None))
        self.motor43Set_pushButton.setText(_translate("Form", "Set", None))
        self.motor43Get_pushButton.setText(_translate("Form", "Get", None))
        self.motor43DisT_pushButton.setText(_translate("Form", "DisT", None))


if __name__ == "__main__":
    import sys
    app = QtGui.QApplication(sys.argv)
    Form = QtGui.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())

